// Code generated by "enumer -type=HardwareItem -json -trimprefix HardwareItem"; DO NOT EDIT.

package hwinfo

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _HardwareItemName = "NoneSysCpuKeyboardBrailleMouseJoystickPrinterScannerChipcardMonitorTvDisplayFramebufferCameraSoundStorageCtrlNetworkCtrlIsdnModemNetworkDiskPartitionCdromFloppyManualUsbCtrlUsbBiosPciIsapnpBridgeHubScsiIdeMemoryDvbPcmciaPcmciaCtrlIeee1394Ieee1394CtrlHotplugHotplugCtrlZipPppoeWlanRedasdDslBlockTapeVbeBluetoothFingerprintMmcCtrlNvmeUnknownAll"

var _HardwareItemIndex = [...]uint16{0, 4, 7, 10, 18, 25, 30, 38, 45, 52, 60, 67, 69, 76, 87, 93, 98, 109, 120, 124, 129, 136, 140, 149, 154, 160, 166, 173, 176, 180, 183, 189, 195, 198, 202, 205, 211, 214, 220, 230, 238, 250, 257, 268, 271, 276, 280, 286, 289, 294, 298, 301, 310, 321, 328, 332, 339, 342}

const _HardwareItemLowerName = "nonesyscpukeyboardbraillemousejoystickprinterscannerchipcardmonitortvdisplayframebuffercamerasoundstoragectrlnetworkctrlisdnmodemnetworkdiskpartitioncdromfloppymanualusbctrlusbbiospciisapnpbridgehubscsiidememorydvbpcmciapcmciactrlieee1394ieee1394ctrlhotplughotplugctrlzippppoewlanredasddslblocktapevbebluetoothfingerprintmmcctrlnvmeunknownall"

func (i HardwareItem) String() string {
	if i < 0 || i >= HardwareItem(len(_HardwareItemIndex)-1) {
		return fmt.Sprintf("HardwareItem(%d)", i)
	}
	return _HardwareItemName[_HardwareItemIndex[i]:_HardwareItemIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _HardwareItemNoOp() {
	var x [1]struct{}
	_ = x[HardwareItemNone-(0)]
	_ = x[HardwareItemSys-(1)]
	_ = x[HardwareItemCpu-(2)]
	_ = x[HardwareItemKeyboard-(3)]
	_ = x[HardwareItemBraille-(4)]
	_ = x[HardwareItemMouse-(5)]
	_ = x[HardwareItemJoystick-(6)]
	_ = x[HardwareItemPrinter-(7)]
	_ = x[HardwareItemScanner-(8)]
	_ = x[HardwareItemChipcard-(9)]
	_ = x[HardwareItemMonitor-(10)]
	_ = x[HardwareItemTv-(11)]
	_ = x[HardwareItemDisplay-(12)]
	_ = x[HardwareItemFramebuffer-(13)]
	_ = x[HardwareItemCamera-(14)]
	_ = x[HardwareItemSound-(15)]
	_ = x[HardwareItemStorageCtrl-(16)]
	_ = x[HardwareItemNetworkCtrl-(17)]
	_ = x[HardwareItemIsdn-(18)]
	_ = x[HardwareItemModem-(19)]
	_ = x[HardwareItemNetwork-(20)]
	_ = x[HardwareItemDisk-(21)]
	_ = x[HardwareItemPartition-(22)]
	_ = x[HardwareItemCdrom-(23)]
	_ = x[HardwareItemFloppy-(24)]
	_ = x[HardwareItemManual-(25)]
	_ = x[HardwareItemUsbCtrl-(26)]
	_ = x[HardwareItemUsb-(27)]
	_ = x[HardwareItemBios-(28)]
	_ = x[HardwareItemPci-(29)]
	_ = x[HardwareItemIsapnp-(30)]
	_ = x[HardwareItemBridge-(31)]
	_ = x[HardwareItemHub-(32)]
	_ = x[HardwareItemScsi-(33)]
	_ = x[HardwareItemIde-(34)]
	_ = x[HardwareItemMemory-(35)]
	_ = x[HardwareItemDvb-(36)]
	_ = x[HardwareItemPcmcia-(37)]
	_ = x[HardwareItemPcmciaCtrl-(38)]
	_ = x[HardwareItemIeee1394-(39)]
	_ = x[HardwareItemIeee1394Ctrl-(40)]
	_ = x[HardwareItemHotplug-(41)]
	_ = x[HardwareItemHotplugCtrl-(42)]
	_ = x[HardwareItemZip-(43)]
	_ = x[HardwareItemPppoe-(44)]
	_ = x[HardwareItemWlan-(45)]
	_ = x[HardwareItemRedasd-(46)]
	_ = x[HardwareItemDsl-(47)]
	_ = x[HardwareItemBlock-(48)]
	_ = x[HardwareItemTape-(49)]
	_ = x[HardwareItemVbe-(50)]
	_ = x[HardwareItemBluetooth-(51)]
	_ = x[HardwareItemFingerprint-(52)]
	_ = x[HardwareItemMmcCtrl-(53)]
	_ = x[HardwareItemNvme-(54)]
	_ = x[HardwareItemUnknown-(55)]
	_ = x[HardwareItemAll-(56)]
}

var _HardwareItemValues = []HardwareItem{HardwareItemNone, HardwareItemSys, HardwareItemCpu, HardwareItemKeyboard, HardwareItemBraille, HardwareItemMouse, HardwareItemJoystick, HardwareItemPrinter, HardwareItemScanner, HardwareItemChipcard, HardwareItemMonitor, HardwareItemTv, HardwareItemDisplay, HardwareItemFramebuffer, HardwareItemCamera, HardwareItemSound, HardwareItemStorageCtrl, HardwareItemNetworkCtrl, HardwareItemIsdn, HardwareItemModem, HardwareItemNetwork, HardwareItemDisk, HardwareItemPartition, HardwareItemCdrom, HardwareItemFloppy, HardwareItemManual, HardwareItemUsbCtrl, HardwareItemUsb, HardwareItemBios, HardwareItemPci, HardwareItemIsapnp, HardwareItemBridge, HardwareItemHub, HardwareItemScsi, HardwareItemIde, HardwareItemMemory, HardwareItemDvb, HardwareItemPcmcia, HardwareItemPcmciaCtrl, HardwareItemIeee1394, HardwareItemIeee1394Ctrl, HardwareItemHotplug, HardwareItemHotplugCtrl, HardwareItemZip, HardwareItemPppoe, HardwareItemWlan, HardwareItemRedasd, HardwareItemDsl, HardwareItemBlock, HardwareItemTape, HardwareItemVbe, HardwareItemBluetooth, HardwareItemFingerprint, HardwareItemMmcCtrl, HardwareItemNvme, HardwareItemUnknown, HardwareItemAll}

var _HardwareItemNameToValueMap = map[string]HardwareItem{
	_HardwareItemName[0:4]:          HardwareItemNone,
	_HardwareItemLowerName[0:4]:     HardwareItemNone,
	_HardwareItemName[4:7]:          HardwareItemSys,
	_HardwareItemLowerName[4:7]:     HardwareItemSys,
	_HardwareItemName[7:10]:         HardwareItemCpu,
	_HardwareItemLowerName[7:10]:    HardwareItemCpu,
	_HardwareItemName[10:18]:        HardwareItemKeyboard,
	_HardwareItemLowerName[10:18]:   HardwareItemKeyboard,
	_HardwareItemName[18:25]:        HardwareItemBraille,
	_HardwareItemLowerName[18:25]:   HardwareItemBraille,
	_HardwareItemName[25:30]:        HardwareItemMouse,
	_HardwareItemLowerName[25:30]:   HardwareItemMouse,
	_HardwareItemName[30:38]:        HardwareItemJoystick,
	_HardwareItemLowerName[30:38]:   HardwareItemJoystick,
	_HardwareItemName[38:45]:        HardwareItemPrinter,
	_HardwareItemLowerName[38:45]:   HardwareItemPrinter,
	_HardwareItemName[45:52]:        HardwareItemScanner,
	_HardwareItemLowerName[45:52]:   HardwareItemScanner,
	_HardwareItemName[52:60]:        HardwareItemChipcard,
	_HardwareItemLowerName[52:60]:   HardwareItemChipcard,
	_HardwareItemName[60:67]:        HardwareItemMonitor,
	_HardwareItemLowerName[60:67]:   HardwareItemMonitor,
	_HardwareItemName[67:69]:        HardwareItemTv,
	_HardwareItemLowerName[67:69]:   HardwareItemTv,
	_HardwareItemName[69:76]:        HardwareItemDisplay,
	_HardwareItemLowerName[69:76]:   HardwareItemDisplay,
	_HardwareItemName[76:87]:        HardwareItemFramebuffer,
	_HardwareItemLowerName[76:87]:   HardwareItemFramebuffer,
	_HardwareItemName[87:93]:        HardwareItemCamera,
	_HardwareItemLowerName[87:93]:   HardwareItemCamera,
	_HardwareItemName[93:98]:        HardwareItemSound,
	_HardwareItemLowerName[93:98]:   HardwareItemSound,
	_HardwareItemName[98:109]:       HardwareItemStorageCtrl,
	_HardwareItemLowerName[98:109]:  HardwareItemStorageCtrl,
	_HardwareItemName[109:120]:      HardwareItemNetworkCtrl,
	_HardwareItemLowerName[109:120]: HardwareItemNetworkCtrl,
	_HardwareItemName[120:124]:      HardwareItemIsdn,
	_HardwareItemLowerName[120:124]: HardwareItemIsdn,
	_HardwareItemName[124:129]:      HardwareItemModem,
	_HardwareItemLowerName[124:129]: HardwareItemModem,
	_HardwareItemName[129:136]:      HardwareItemNetwork,
	_HardwareItemLowerName[129:136]: HardwareItemNetwork,
	_HardwareItemName[136:140]:      HardwareItemDisk,
	_HardwareItemLowerName[136:140]: HardwareItemDisk,
	_HardwareItemName[140:149]:      HardwareItemPartition,
	_HardwareItemLowerName[140:149]: HardwareItemPartition,
	_HardwareItemName[149:154]:      HardwareItemCdrom,
	_HardwareItemLowerName[149:154]: HardwareItemCdrom,
	_HardwareItemName[154:160]:      HardwareItemFloppy,
	_HardwareItemLowerName[154:160]: HardwareItemFloppy,
	_HardwareItemName[160:166]:      HardwareItemManual,
	_HardwareItemLowerName[160:166]: HardwareItemManual,
	_HardwareItemName[166:173]:      HardwareItemUsbCtrl,
	_HardwareItemLowerName[166:173]: HardwareItemUsbCtrl,
	_HardwareItemName[173:176]:      HardwareItemUsb,
	_HardwareItemLowerName[173:176]: HardwareItemUsb,
	_HardwareItemName[176:180]:      HardwareItemBios,
	_HardwareItemLowerName[176:180]: HardwareItemBios,
	_HardwareItemName[180:183]:      HardwareItemPci,
	_HardwareItemLowerName[180:183]: HardwareItemPci,
	_HardwareItemName[183:189]:      HardwareItemIsapnp,
	_HardwareItemLowerName[183:189]: HardwareItemIsapnp,
	_HardwareItemName[189:195]:      HardwareItemBridge,
	_HardwareItemLowerName[189:195]: HardwareItemBridge,
	_HardwareItemName[195:198]:      HardwareItemHub,
	_HardwareItemLowerName[195:198]: HardwareItemHub,
	_HardwareItemName[198:202]:      HardwareItemScsi,
	_HardwareItemLowerName[198:202]: HardwareItemScsi,
	_HardwareItemName[202:205]:      HardwareItemIde,
	_HardwareItemLowerName[202:205]: HardwareItemIde,
	_HardwareItemName[205:211]:      HardwareItemMemory,
	_HardwareItemLowerName[205:211]: HardwareItemMemory,
	_HardwareItemName[211:214]:      HardwareItemDvb,
	_HardwareItemLowerName[211:214]: HardwareItemDvb,
	_HardwareItemName[214:220]:      HardwareItemPcmcia,
	_HardwareItemLowerName[214:220]: HardwareItemPcmcia,
	_HardwareItemName[220:230]:      HardwareItemPcmciaCtrl,
	_HardwareItemLowerName[220:230]: HardwareItemPcmciaCtrl,
	_HardwareItemName[230:238]:      HardwareItemIeee1394,
	_HardwareItemLowerName[230:238]: HardwareItemIeee1394,
	_HardwareItemName[238:250]:      HardwareItemIeee1394Ctrl,
	_HardwareItemLowerName[238:250]: HardwareItemIeee1394Ctrl,
	_HardwareItemName[250:257]:      HardwareItemHotplug,
	_HardwareItemLowerName[250:257]: HardwareItemHotplug,
	_HardwareItemName[257:268]:      HardwareItemHotplugCtrl,
	_HardwareItemLowerName[257:268]: HardwareItemHotplugCtrl,
	_HardwareItemName[268:271]:      HardwareItemZip,
	_HardwareItemLowerName[268:271]: HardwareItemZip,
	_HardwareItemName[271:276]:      HardwareItemPppoe,
	_HardwareItemLowerName[271:276]: HardwareItemPppoe,
	_HardwareItemName[276:280]:      HardwareItemWlan,
	_HardwareItemLowerName[276:280]: HardwareItemWlan,
	_HardwareItemName[280:286]:      HardwareItemRedasd,
	_HardwareItemLowerName[280:286]: HardwareItemRedasd,
	_HardwareItemName[286:289]:      HardwareItemDsl,
	_HardwareItemLowerName[286:289]: HardwareItemDsl,
	_HardwareItemName[289:294]:      HardwareItemBlock,
	_HardwareItemLowerName[289:294]: HardwareItemBlock,
	_HardwareItemName[294:298]:      HardwareItemTape,
	_HardwareItemLowerName[294:298]: HardwareItemTape,
	_HardwareItemName[298:301]:      HardwareItemVbe,
	_HardwareItemLowerName[298:301]: HardwareItemVbe,
	_HardwareItemName[301:310]:      HardwareItemBluetooth,
	_HardwareItemLowerName[301:310]: HardwareItemBluetooth,
	_HardwareItemName[310:321]:      HardwareItemFingerprint,
	_HardwareItemLowerName[310:321]: HardwareItemFingerprint,
	_HardwareItemName[321:328]:      HardwareItemMmcCtrl,
	_HardwareItemLowerName[321:328]: HardwareItemMmcCtrl,
	_HardwareItemName[328:332]:      HardwareItemNvme,
	_HardwareItemLowerName[328:332]: HardwareItemNvme,
	_HardwareItemName[332:339]:      HardwareItemUnknown,
	_HardwareItemLowerName[332:339]: HardwareItemUnknown,
	_HardwareItemName[339:342]:      HardwareItemAll,
	_HardwareItemLowerName[339:342]: HardwareItemAll,
}

var _HardwareItemNames = []string{
	_HardwareItemName[0:4],
	_HardwareItemName[4:7],
	_HardwareItemName[7:10],
	_HardwareItemName[10:18],
	_HardwareItemName[18:25],
	_HardwareItemName[25:30],
	_HardwareItemName[30:38],
	_HardwareItemName[38:45],
	_HardwareItemName[45:52],
	_HardwareItemName[52:60],
	_HardwareItemName[60:67],
	_HardwareItemName[67:69],
	_HardwareItemName[69:76],
	_HardwareItemName[76:87],
	_HardwareItemName[87:93],
	_HardwareItemName[93:98],
	_HardwareItemName[98:109],
	_HardwareItemName[109:120],
	_HardwareItemName[120:124],
	_HardwareItemName[124:129],
	_HardwareItemName[129:136],
	_HardwareItemName[136:140],
	_HardwareItemName[140:149],
	_HardwareItemName[149:154],
	_HardwareItemName[154:160],
	_HardwareItemName[160:166],
	_HardwareItemName[166:173],
	_HardwareItemName[173:176],
	_HardwareItemName[176:180],
	_HardwareItemName[180:183],
	_HardwareItemName[183:189],
	_HardwareItemName[189:195],
	_HardwareItemName[195:198],
	_HardwareItemName[198:202],
	_HardwareItemName[202:205],
	_HardwareItemName[205:211],
	_HardwareItemName[211:214],
	_HardwareItemName[214:220],
	_HardwareItemName[220:230],
	_HardwareItemName[230:238],
	_HardwareItemName[238:250],
	_HardwareItemName[250:257],
	_HardwareItemName[257:268],
	_HardwareItemName[268:271],
	_HardwareItemName[271:276],
	_HardwareItemName[276:280],
	_HardwareItemName[280:286],
	_HardwareItemName[286:289],
	_HardwareItemName[289:294],
	_HardwareItemName[294:298],
	_HardwareItemName[298:301],
	_HardwareItemName[301:310],
	_HardwareItemName[310:321],
	_HardwareItemName[321:328],
	_HardwareItemName[328:332],
	_HardwareItemName[332:339],
	_HardwareItemName[339:342],
}

// HardwareItemString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func HardwareItemString(s string) (HardwareItem, error) {
	if val, ok := _HardwareItemNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _HardwareItemNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to HardwareItem values", s)
}

// HardwareItemValues returns all values of the enum
func HardwareItemValues() []HardwareItem {
	return _HardwareItemValues
}

// HardwareItemStrings returns a slice of all String values of the enum
func HardwareItemStrings() []string {
	strs := make([]string, len(_HardwareItemNames))
	copy(strs, _HardwareItemNames)
	return strs
}

// IsAHardwareItem returns "true" if the value is listed in the enum definition. "false" otherwise
func (i HardwareItem) IsAHardwareItem() bool {
	for _, v := range _HardwareItemValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for HardwareItem
func (i HardwareItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for HardwareItem
func (i *HardwareItem) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("HardwareItem should be a string, got %s", data)
	}

	var err error
	*i, err = HardwareItemString(s)
	return err
}
