// Code generated by "enumer -type=HardwareItem"; DO NOT EDIT.

package hwinfo

import (
	"fmt"
	"strings"
)

const _HardwareItemName = "HardwareItemNoneHardwareItemSysHardwareItemCpuHardwareItemKeyboardHardwareItemBrailleHardwareItemMouseHardwareItemJoystickHardwareItemPrinterHardwareItemScannerHardwareItemChipcardHardwareItemMonitorHardwareItemTvHardwareItemDisplayHardwareItemFramebufferHardwareItemCameraHardwareItemSoundHardwareItemStorageCtrlHardwareItemNetworkCtrlHardwareItemIsdnHardwareItemModemHardwareItemNetworkHardwareItemDiskHardwareItemPartitionHardwareItemCdromHardwareItemFloppyHardwareItemManualHardwareItemUsbCtrlHardwareItemUsbHardwareItemBiosHardwareItemPciHardwareItemIsapnpHardwareItemBridgeHardwareItemHubHardwareItemScsiHardwareItemIdeHardwareItemMemoryHardwareItemDvbHardwareItemPcmciaHardwareItemPcmciaCtrlHardwareItemIeee1394HardwareItemIeee1394CtrlHardwareItemHotplugHardwareItemHotplugCtrlHardwareItemZipHardwareItemPppoeHardwareItemWlanHardwareItemRedasdHardwareItemDslHardwareItemBlockHardwareItemTapeHardwareItemVbeHardwareItemBluetoothHardwareItemFingerprintHardwareItemMmcCtrlHardwareItemNvmeHardwareItemUnknownHardwareItemAll"

var _HardwareItemIndex = [...]uint16{0, 16, 31, 46, 66, 85, 102, 122, 141, 160, 180, 199, 213, 232, 255, 273, 290, 313, 336, 352, 369, 388, 404, 425, 442, 460, 478, 497, 512, 528, 543, 561, 579, 594, 610, 625, 643, 658, 676, 698, 718, 742, 761, 784, 799, 816, 832, 850, 865, 882, 898, 913, 934, 957, 976, 992, 1011, 1026}

const _HardwareItemLowerName = "hardwareitemnonehardwareitemsyshardwareitemcpuhardwareitemkeyboardhardwareitembraillehardwareitemmousehardwareitemjoystickhardwareitemprinterhardwareitemscannerhardwareitemchipcardhardwareitemmonitorhardwareitemtvhardwareitemdisplayhardwareitemframebufferhardwareitemcamerahardwareitemsoundhardwareitemstoragectrlhardwareitemnetworkctrlhardwareitemisdnhardwareitemmodemhardwareitemnetworkhardwareitemdiskhardwareitempartitionhardwareitemcdromhardwareitemfloppyhardwareitemmanualhardwareitemusbctrlhardwareitemusbhardwareitembioshardwareitempcihardwareitemisapnphardwareitembridgehardwareitemhubhardwareitemscsihardwareitemidehardwareitemmemoryhardwareitemdvbhardwareitempcmciahardwareitempcmciactrlhardwareitemieee1394hardwareitemieee1394ctrlhardwareitemhotplughardwareitemhotplugctrlhardwareitemziphardwareitempppoehardwareitemwlanhardwareitemredasdhardwareitemdslhardwareitemblockhardwareitemtapehardwareitemvbehardwareitembluetoothhardwareitemfingerprinthardwareitemmmcctrlhardwareitemnvmehardwareitemunknownhardwareitemall"

func (i HardwareItem) String() string {
	if i < 0 || i >= HardwareItem(len(_HardwareItemIndex)-1) {
		return fmt.Sprintf("HardwareItem(%d)", i)
	}
	return _HardwareItemName[_HardwareItemIndex[i]:_HardwareItemIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _HardwareItemNoOp() {
	var x [1]struct{}
	_ = x[HardwareItemNone-(0)]
	_ = x[HardwareItemSys-(1)]
	_ = x[HardwareItemCpu-(2)]
	_ = x[HardwareItemKeyboard-(3)]
	_ = x[HardwareItemBraille-(4)]
	_ = x[HardwareItemMouse-(5)]
	_ = x[HardwareItemJoystick-(6)]
	_ = x[HardwareItemPrinter-(7)]
	_ = x[HardwareItemScanner-(8)]
	_ = x[HardwareItemChipcard-(9)]
	_ = x[HardwareItemMonitor-(10)]
	_ = x[HardwareItemTv-(11)]
	_ = x[HardwareItemDisplay-(12)]
	_ = x[HardwareItemFramebuffer-(13)]
	_ = x[HardwareItemCamera-(14)]
	_ = x[HardwareItemSound-(15)]
	_ = x[HardwareItemStorageCtrl-(16)]
	_ = x[HardwareItemNetworkCtrl-(17)]
	_ = x[HardwareItemIsdn-(18)]
	_ = x[HardwareItemModem-(19)]
	_ = x[HardwareItemNetwork-(20)]
	_ = x[HardwareItemDisk-(21)]
	_ = x[HardwareItemPartition-(22)]
	_ = x[HardwareItemCdrom-(23)]
	_ = x[HardwareItemFloppy-(24)]
	_ = x[HardwareItemManual-(25)]
	_ = x[HardwareItemUsbCtrl-(26)]
	_ = x[HardwareItemUsb-(27)]
	_ = x[HardwareItemBios-(28)]
	_ = x[HardwareItemPci-(29)]
	_ = x[HardwareItemIsapnp-(30)]
	_ = x[HardwareItemBridge-(31)]
	_ = x[HardwareItemHub-(32)]
	_ = x[HardwareItemScsi-(33)]
	_ = x[HardwareItemIde-(34)]
	_ = x[HardwareItemMemory-(35)]
	_ = x[HardwareItemDvb-(36)]
	_ = x[HardwareItemPcmcia-(37)]
	_ = x[HardwareItemPcmciaCtrl-(38)]
	_ = x[HardwareItemIeee1394-(39)]
	_ = x[HardwareItemIeee1394Ctrl-(40)]
	_ = x[HardwareItemHotplug-(41)]
	_ = x[HardwareItemHotplugCtrl-(42)]
	_ = x[HardwareItemZip-(43)]
	_ = x[HardwareItemPppoe-(44)]
	_ = x[HardwareItemWlan-(45)]
	_ = x[HardwareItemRedasd-(46)]
	_ = x[HardwareItemDsl-(47)]
	_ = x[HardwareItemBlock-(48)]
	_ = x[HardwareItemTape-(49)]
	_ = x[HardwareItemVbe-(50)]
	_ = x[HardwareItemBluetooth-(51)]
	_ = x[HardwareItemFingerprint-(52)]
	_ = x[HardwareItemMmcCtrl-(53)]
	_ = x[HardwareItemNvme-(54)]
	_ = x[HardwareItemUnknown-(55)]
	_ = x[HardwareItemAll-(56)]
}

var _HardwareItemValues = []HardwareItem{HardwareItemNone, HardwareItemSys, HardwareItemCpu, HardwareItemKeyboard, HardwareItemBraille, HardwareItemMouse, HardwareItemJoystick, HardwareItemPrinter, HardwareItemScanner, HardwareItemChipcard, HardwareItemMonitor, HardwareItemTv, HardwareItemDisplay, HardwareItemFramebuffer, HardwareItemCamera, HardwareItemSound, HardwareItemStorageCtrl, HardwareItemNetworkCtrl, HardwareItemIsdn, HardwareItemModem, HardwareItemNetwork, HardwareItemDisk, HardwareItemPartition, HardwareItemCdrom, HardwareItemFloppy, HardwareItemManual, HardwareItemUsbCtrl, HardwareItemUsb, HardwareItemBios, HardwareItemPci, HardwareItemIsapnp, HardwareItemBridge, HardwareItemHub, HardwareItemScsi, HardwareItemIde, HardwareItemMemory, HardwareItemDvb, HardwareItemPcmcia, HardwareItemPcmciaCtrl, HardwareItemIeee1394, HardwareItemIeee1394Ctrl, HardwareItemHotplug, HardwareItemHotplugCtrl, HardwareItemZip, HardwareItemPppoe, HardwareItemWlan, HardwareItemRedasd, HardwareItemDsl, HardwareItemBlock, HardwareItemTape, HardwareItemVbe, HardwareItemBluetooth, HardwareItemFingerprint, HardwareItemMmcCtrl, HardwareItemNvme, HardwareItemUnknown, HardwareItemAll}

var _HardwareItemNameToValueMap = map[string]HardwareItem{
	_HardwareItemName[0:16]:           HardwareItemNone,
	_HardwareItemLowerName[0:16]:      HardwareItemNone,
	_HardwareItemName[16:31]:          HardwareItemSys,
	_HardwareItemLowerName[16:31]:     HardwareItemSys,
	_HardwareItemName[31:46]:          HardwareItemCpu,
	_HardwareItemLowerName[31:46]:     HardwareItemCpu,
	_HardwareItemName[46:66]:          HardwareItemKeyboard,
	_HardwareItemLowerName[46:66]:     HardwareItemKeyboard,
	_HardwareItemName[66:85]:          HardwareItemBraille,
	_HardwareItemLowerName[66:85]:     HardwareItemBraille,
	_HardwareItemName[85:102]:         HardwareItemMouse,
	_HardwareItemLowerName[85:102]:    HardwareItemMouse,
	_HardwareItemName[102:122]:        HardwareItemJoystick,
	_HardwareItemLowerName[102:122]:   HardwareItemJoystick,
	_HardwareItemName[122:141]:        HardwareItemPrinter,
	_HardwareItemLowerName[122:141]:   HardwareItemPrinter,
	_HardwareItemName[141:160]:        HardwareItemScanner,
	_HardwareItemLowerName[141:160]:   HardwareItemScanner,
	_HardwareItemName[160:180]:        HardwareItemChipcard,
	_HardwareItemLowerName[160:180]:   HardwareItemChipcard,
	_HardwareItemName[180:199]:        HardwareItemMonitor,
	_HardwareItemLowerName[180:199]:   HardwareItemMonitor,
	_HardwareItemName[199:213]:        HardwareItemTv,
	_HardwareItemLowerName[199:213]:   HardwareItemTv,
	_HardwareItemName[213:232]:        HardwareItemDisplay,
	_HardwareItemLowerName[213:232]:   HardwareItemDisplay,
	_HardwareItemName[232:255]:        HardwareItemFramebuffer,
	_HardwareItemLowerName[232:255]:   HardwareItemFramebuffer,
	_HardwareItemName[255:273]:        HardwareItemCamera,
	_HardwareItemLowerName[255:273]:   HardwareItemCamera,
	_HardwareItemName[273:290]:        HardwareItemSound,
	_HardwareItemLowerName[273:290]:   HardwareItemSound,
	_HardwareItemName[290:313]:        HardwareItemStorageCtrl,
	_HardwareItemLowerName[290:313]:   HardwareItemStorageCtrl,
	_HardwareItemName[313:336]:        HardwareItemNetworkCtrl,
	_HardwareItemLowerName[313:336]:   HardwareItemNetworkCtrl,
	_HardwareItemName[336:352]:        HardwareItemIsdn,
	_HardwareItemLowerName[336:352]:   HardwareItemIsdn,
	_HardwareItemName[352:369]:        HardwareItemModem,
	_HardwareItemLowerName[352:369]:   HardwareItemModem,
	_HardwareItemName[369:388]:        HardwareItemNetwork,
	_HardwareItemLowerName[369:388]:   HardwareItemNetwork,
	_HardwareItemName[388:404]:        HardwareItemDisk,
	_HardwareItemLowerName[388:404]:   HardwareItemDisk,
	_HardwareItemName[404:425]:        HardwareItemPartition,
	_HardwareItemLowerName[404:425]:   HardwareItemPartition,
	_HardwareItemName[425:442]:        HardwareItemCdrom,
	_HardwareItemLowerName[425:442]:   HardwareItemCdrom,
	_HardwareItemName[442:460]:        HardwareItemFloppy,
	_HardwareItemLowerName[442:460]:   HardwareItemFloppy,
	_HardwareItemName[460:478]:        HardwareItemManual,
	_HardwareItemLowerName[460:478]:   HardwareItemManual,
	_HardwareItemName[478:497]:        HardwareItemUsbCtrl,
	_HardwareItemLowerName[478:497]:   HardwareItemUsbCtrl,
	_HardwareItemName[497:512]:        HardwareItemUsb,
	_HardwareItemLowerName[497:512]:   HardwareItemUsb,
	_HardwareItemName[512:528]:        HardwareItemBios,
	_HardwareItemLowerName[512:528]:   HardwareItemBios,
	_HardwareItemName[528:543]:        HardwareItemPci,
	_HardwareItemLowerName[528:543]:   HardwareItemPci,
	_HardwareItemName[543:561]:        HardwareItemIsapnp,
	_HardwareItemLowerName[543:561]:   HardwareItemIsapnp,
	_HardwareItemName[561:579]:        HardwareItemBridge,
	_HardwareItemLowerName[561:579]:   HardwareItemBridge,
	_HardwareItemName[579:594]:        HardwareItemHub,
	_HardwareItemLowerName[579:594]:   HardwareItemHub,
	_HardwareItemName[594:610]:        HardwareItemScsi,
	_HardwareItemLowerName[594:610]:   HardwareItemScsi,
	_HardwareItemName[610:625]:        HardwareItemIde,
	_HardwareItemLowerName[610:625]:   HardwareItemIde,
	_HardwareItemName[625:643]:        HardwareItemMemory,
	_HardwareItemLowerName[625:643]:   HardwareItemMemory,
	_HardwareItemName[643:658]:        HardwareItemDvb,
	_HardwareItemLowerName[643:658]:   HardwareItemDvb,
	_HardwareItemName[658:676]:        HardwareItemPcmcia,
	_HardwareItemLowerName[658:676]:   HardwareItemPcmcia,
	_HardwareItemName[676:698]:        HardwareItemPcmciaCtrl,
	_HardwareItemLowerName[676:698]:   HardwareItemPcmciaCtrl,
	_HardwareItemName[698:718]:        HardwareItemIeee1394,
	_HardwareItemLowerName[698:718]:   HardwareItemIeee1394,
	_HardwareItemName[718:742]:        HardwareItemIeee1394Ctrl,
	_HardwareItemLowerName[718:742]:   HardwareItemIeee1394Ctrl,
	_HardwareItemName[742:761]:        HardwareItemHotplug,
	_HardwareItemLowerName[742:761]:   HardwareItemHotplug,
	_HardwareItemName[761:784]:        HardwareItemHotplugCtrl,
	_HardwareItemLowerName[761:784]:   HardwareItemHotplugCtrl,
	_HardwareItemName[784:799]:        HardwareItemZip,
	_HardwareItemLowerName[784:799]:   HardwareItemZip,
	_HardwareItemName[799:816]:        HardwareItemPppoe,
	_HardwareItemLowerName[799:816]:   HardwareItemPppoe,
	_HardwareItemName[816:832]:        HardwareItemWlan,
	_HardwareItemLowerName[816:832]:   HardwareItemWlan,
	_HardwareItemName[832:850]:        HardwareItemRedasd,
	_HardwareItemLowerName[832:850]:   HardwareItemRedasd,
	_HardwareItemName[850:865]:        HardwareItemDsl,
	_HardwareItemLowerName[850:865]:   HardwareItemDsl,
	_HardwareItemName[865:882]:        HardwareItemBlock,
	_HardwareItemLowerName[865:882]:   HardwareItemBlock,
	_HardwareItemName[882:898]:        HardwareItemTape,
	_HardwareItemLowerName[882:898]:   HardwareItemTape,
	_HardwareItemName[898:913]:        HardwareItemVbe,
	_HardwareItemLowerName[898:913]:   HardwareItemVbe,
	_HardwareItemName[913:934]:        HardwareItemBluetooth,
	_HardwareItemLowerName[913:934]:   HardwareItemBluetooth,
	_HardwareItemName[934:957]:        HardwareItemFingerprint,
	_HardwareItemLowerName[934:957]:   HardwareItemFingerprint,
	_HardwareItemName[957:976]:        HardwareItemMmcCtrl,
	_HardwareItemLowerName[957:976]:   HardwareItemMmcCtrl,
	_HardwareItemName[976:992]:        HardwareItemNvme,
	_HardwareItemLowerName[976:992]:   HardwareItemNvme,
	_HardwareItemName[992:1011]:       HardwareItemUnknown,
	_HardwareItemLowerName[992:1011]:  HardwareItemUnknown,
	_HardwareItemName[1011:1026]:      HardwareItemAll,
	_HardwareItemLowerName[1011:1026]: HardwareItemAll,
}

var _HardwareItemNames = []string{
	_HardwareItemName[0:16],
	_HardwareItemName[16:31],
	_HardwareItemName[31:46],
	_HardwareItemName[46:66],
	_HardwareItemName[66:85],
	_HardwareItemName[85:102],
	_HardwareItemName[102:122],
	_HardwareItemName[122:141],
	_HardwareItemName[141:160],
	_HardwareItemName[160:180],
	_HardwareItemName[180:199],
	_HardwareItemName[199:213],
	_HardwareItemName[213:232],
	_HardwareItemName[232:255],
	_HardwareItemName[255:273],
	_HardwareItemName[273:290],
	_HardwareItemName[290:313],
	_HardwareItemName[313:336],
	_HardwareItemName[336:352],
	_HardwareItemName[352:369],
	_HardwareItemName[369:388],
	_HardwareItemName[388:404],
	_HardwareItemName[404:425],
	_HardwareItemName[425:442],
	_HardwareItemName[442:460],
	_HardwareItemName[460:478],
	_HardwareItemName[478:497],
	_HardwareItemName[497:512],
	_HardwareItemName[512:528],
	_HardwareItemName[528:543],
	_HardwareItemName[543:561],
	_HardwareItemName[561:579],
	_HardwareItemName[579:594],
	_HardwareItemName[594:610],
	_HardwareItemName[610:625],
	_HardwareItemName[625:643],
	_HardwareItemName[643:658],
	_HardwareItemName[658:676],
	_HardwareItemName[676:698],
	_HardwareItemName[698:718],
	_HardwareItemName[718:742],
	_HardwareItemName[742:761],
	_HardwareItemName[761:784],
	_HardwareItemName[784:799],
	_HardwareItemName[799:816],
	_HardwareItemName[816:832],
	_HardwareItemName[832:850],
	_HardwareItemName[850:865],
	_HardwareItemName[865:882],
	_HardwareItemName[882:898],
	_HardwareItemName[898:913],
	_HardwareItemName[913:934],
	_HardwareItemName[934:957],
	_HardwareItemName[957:976],
	_HardwareItemName[976:992],
	_HardwareItemName[992:1011],
	_HardwareItemName[1011:1026],
}

// HardwareItemString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func HardwareItemString(s string) (HardwareItem, error) {
	if val, ok := _HardwareItemNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _HardwareItemNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to HardwareItem values", s)
}

// HardwareItemValues returns all values of the enum
func HardwareItemValues() []HardwareItem {
	return _HardwareItemValues
}

// HardwareItemStrings returns a slice of all String values of the enum
func HardwareItemStrings() []string {
	strs := make([]string, len(_HardwareItemNames))
	copy(strs, _HardwareItemNames)
	return strs
}

// IsAHardwareItem returns "true" if the value is listed in the enum definition. "false" otherwise
func (i HardwareItem) IsAHardwareItem() bool {
	for _, v := range _HardwareItemValues {
		if i == v {
			return true
		}
	}
	return false
}
