// Code generated by "enumer -type=ProbeFeature -json -trimprefix ProbeFeature"; DO NOT EDIT.

package hwinfo

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _ProbeFeatureName = "MemoryPciIsapnpNetFloppyMiscMiscSerialMiscParMiscFloppySerialCpuBiosMonitorMouseScsiUsbUsbModsAdbModemModemUsbParallelParallelLpParallelZipIsaIsaIsdnIsdnKbdPromSbusIntBrailleBrailleAlvaBrailleFhpBrailleHtIgnx11SysBiosVbeIsapnpOldIsapnpNewIsapnpModBrailleBaumManualFbVethPppoeScanPcmciaForkParallelImmS390CpuemuSysfsS390disksUdevBlockBlockCdromBlockPartEddEddModBiosDdcBiosFbBiosModeInputBlockModsBiosVesaCpuemuDebugScsiNoserialWlanBiosCrcHalBiosVramBiosAcpiBiosDdcPortsModulesPataNetEepromX86emuMaxLxrcDefaultAll"

var _ProbeFeatureIndex = [...]uint16{0, 6, 9, 15, 18, 24, 28, 38, 45, 55, 61, 64, 68, 75, 80, 84, 87, 94, 97, 102, 110, 118, 128, 139, 142, 149, 153, 156, 160, 164, 167, 174, 185, 195, 204, 210, 213, 220, 229, 238, 247, 258, 264, 266, 270, 275, 279, 285, 289, 300, 304, 310, 315, 324, 328, 333, 343, 352, 355, 361, 368, 374, 382, 387, 396, 404, 415, 427, 431, 438, 441, 449, 457, 469, 480, 489, 495, 498, 502, 509, 512}

const _ProbeFeatureLowerName = "memorypciisapnpnetfloppymiscmiscserialmiscparmiscfloppyserialcpubiosmonitormousescsiusbusbmodsadbmodemmodemusbparallelparallellpparallelzipisaisaisdnisdnkbdpromsbusintbraillebraillealvabraillefhpbraillehtignx11sysbiosvbeisapnpoldisapnpnewisapnpmodbraillebaummanualfbvethpppoescanpcmciaforkparallelimms390cpuemusysfss390disksudevblockblockcdromblockparteddeddmodbiosddcbiosfbbiosmodeinputblockmodsbiosvesacpuemudebugscsinoserialwlanbioscrchalbiosvrambiosacpibiosddcportsmodulespataneteepromx86emumaxlxrcdefaultall"

func (i ProbeFeature) String() string {
	i -= 1
	if i < 0 || i >= ProbeFeature(len(_ProbeFeatureIndex)-1) {
		return fmt.Sprintf("ProbeFeature(%d)", i+1)
	}
	return _ProbeFeatureName[_ProbeFeatureIndex[i]:_ProbeFeatureIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ProbeFeatureNoOp() {
	var x [1]struct{}
	_ = x[ProbeFeatureMemory-(1)]
	_ = x[ProbeFeaturePci-(2)]
	_ = x[ProbeFeatureIsapnp-(3)]
	_ = x[ProbeFeatureNet-(4)]
	_ = x[ProbeFeatureFloppy-(5)]
	_ = x[ProbeFeatureMisc-(6)]
	_ = x[ProbeFeatureMiscSerial-(7)]
	_ = x[ProbeFeatureMiscPar-(8)]
	_ = x[ProbeFeatureMiscFloppy-(9)]
	_ = x[ProbeFeatureSerial-(10)]
	_ = x[ProbeFeatureCpu-(11)]
	_ = x[ProbeFeatureBios-(12)]
	_ = x[ProbeFeatureMonitor-(13)]
	_ = x[ProbeFeatureMouse-(14)]
	_ = x[ProbeFeatureScsi-(15)]
	_ = x[ProbeFeatureUsb-(16)]
	_ = x[ProbeFeatureUsbMods-(17)]
	_ = x[ProbeFeatureAdb-(18)]
	_ = x[ProbeFeatureModem-(19)]
	_ = x[ProbeFeatureModemUsb-(20)]
	_ = x[ProbeFeatureParallel-(21)]
	_ = x[ProbeFeatureParallelLp-(22)]
	_ = x[ProbeFeatureParallelZip-(23)]
	_ = x[ProbeFeatureIsa-(24)]
	_ = x[ProbeFeatureIsaIsdn-(25)]
	_ = x[ProbeFeatureIsdn-(26)]
	_ = x[ProbeFeatureKbd-(27)]
	_ = x[ProbeFeatureProm-(28)]
	_ = x[ProbeFeatureSbus-(29)]
	_ = x[ProbeFeatureInt-(30)]
	_ = x[ProbeFeatureBraille-(31)]
	_ = x[ProbeFeatureBrailleAlva-(32)]
	_ = x[ProbeFeatureBrailleFhp-(33)]
	_ = x[ProbeFeatureBrailleHt-(34)]
	_ = x[ProbeFeatureIgnx11-(35)]
	_ = x[ProbeFeatureSys-(36)]
	_ = x[ProbeFeatureBiosVbe-(37)]
	_ = x[ProbeFeatureIsapnpOld-(38)]
	_ = x[ProbeFeatureIsapnpNew-(39)]
	_ = x[ProbeFeatureIsapnpMod-(40)]
	_ = x[ProbeFeatureBrailleBaum-(41)]
	_ = x[ProbeFeatureManual-(42)]
	_ = x[ProbeFeatureFb-(43)]
	_ = x[ProbeFeatureVeth-(44)]
	_ = x[ProbeFeaturePppoe-(45)]
	_ = x[ProbeFeatureScan-(46)]
	_ = x[ProbeFeaturePcmcia-(47)]
	_ = x[ProbeFeatureFork-(48)]
	_ = x[ProbeFeatureParallelImm-(49)]
	_ = x[ProbeFeatureS390-(50)]
	_ = x[ProbeFeatureCpuemu-(51)]
	_ = x[ProbeFeatureSysfs-(52)]
	_ = x[ProbeFeatureS390disks-(53)]
	_ = x[ProbeFeatureUdev-(54)]
	_ = x[ProbeFeatureBlock-(55)]
	_ = x[ProbeFeatureBlockCdrom-(56)]
	_ = x[ProbeFeatureBlockPart-(57)]
	_ = x[ProbeFeatureEdd-(58)]
	_ = x[ProbeFeatureEddMod-(59)]
	_ = x[ProbeFeatureBiosDdc-(60)]
	_ = x[ProbeFeatureBiosFb-(61)]
	_ = x[ProbeFeatureBiosMode-(62)]
	_ = x[ProbeFeatureInput-(63)]
	_ = x[ProbeFeatureBlockMods-(64)]
	_ = x[ProbeFeatureBiosVesa-(65)]
	_ = x[ProbeFeatureCpuemuDebug-(66)]
	_ = x[ProbeFeatureScsiNoserial-(67)]
	_ = x[ProbeFeatureWlan-(68)]
	_ = x[ProbeFeatureBiosCrc-(69)]
	_ = x[ProbeFeatureHal-(70)]
	_ = x[ProbeFeatureBiosVram-(71)]
	_ = x[ProbeFeatureBiosAcpi-(72)]
	_ = x[ProbeFeatureBiosDdcPorts-(73)]
	_ = x[ProbeFeatureModulesPata-(74)]
	_ = x[ProbeFeatureNetEeprom-(75)]
	_ = x[ProbeFeatureX86emu-(76)]
	_ = x[ProbeFeatureMax-(77)]
	_ = x[ProbeFeatureLxrc-(78)]
	_ = x[ProbeFeatureDefault-(79)]
	_ = x[ProbeFeatureAll-(80)]
}

var _ProbeFeatureValues = []ProbeFeature{ProbeFeatureMemory, ProbeFeaturePci, ProbeFeatureIsapnp, ProbeFeatureNet, ProbeFeatureFloppy, ProbeFeatureMisc, ProbeFeatureMiscSerial, ProbeFeatureMiscPar, ProbeFeatureMiscFloppy, ProbeFeatureSerial, ProbeFeatureCpu, ProbeFeatureBios, ProbeFeatureMonitor, ProbeFeatureMouse, ProbeFeatureScsi, ProbeFeatureUsb, ProbeFeatureUsbMods, ProbeFeatureAdb, ProbeFeatureModem, ProbeFeatureModemUsb, ProbeFeatureParallel, ProbeFeatureParallelLp, ProbeFeatureParallelZip, ProbeFeatureIsa, ProbeFeatureIsaIsdn, ProbeFeatureIsdn, ProbeFeatureKbd, ProbeFeatureProm, ProbeFeatureSbus, ProbeFeatureInt, ProbeFeatureBraille, ProbeFeatureBrailleAlva, ProbeFeatureBrailleFhp, ProbeFeatureBrailleHt, ProbeFeatureIgnx11, ProbeFeatureSys, ProbeFeatureBiosVbe, ProbeFeatureIsapnpOld, ProbeFeatureIsapnpNew, ProbeFeatureIsapnpMod, ProbeFeatureBrailleBaum, ProbeFeatureManual, ProbeFeatureFb, ProbeFeatureVeth, ProbeFeaturePppoe, ProbeFeatureScan, ProbeFeaturePcmcia, ProbeFeatureFork, ProbeFeatureParallelImm, ProbeFeatureS390, ProbeFeatureCpuemu, ProbeFeatureSysfs, ProbeFeatureS390disks, ProbeFeatureUdev, ProbeFeatureBlock, ProbeFeatureBlockCdrom, ProbeFeatureBlockPart, ProbeFeatureEdd, ProbeFeatureEddMod, ProbeFeatureBiosDdc, ProbeFeatureBiosFb, ProbeFeatureBiosMode, ProbeFeatureInput, ProbeFeatureBlockMods, ProbeFeatureBiosVesa, ProbeFeatureCpuemuDebug, ProbeFeatureScsiNoserial, ProbeFeatureWlan, ProbeFeatureBiosCrc, ProbeFeatureHal, ProbeFeatureBiosVram, ProbeFeatureBiosAcpi, ProbeFeatureBiosDdcPorts, ProbeFeatureModulesPata, ProbeFeatureNetEeprom, ProbeFeatureX86emu, ProbeFeatureMax, ProbeFeatureLxrc, ProbeFeatureDefault, ProbeFeatureAll}

var _ProbeFeatureNameToValueMap = map[string]ProbeFeature{
	_ProbeFeatureName[0:6]:          ProbeFeatureMemory,
	_ProbeFeatureLowerName[0:6]:     ProbeFeatureMemory,
	_ProbeFeatureName[6:9]:          ProbeFeaturePci,
	_ProbeFeatureLowerName[6:9]:     ProbeFeaturePci,
	_ProbeFeatureName[9:15]:         ProbeFeatureIsapnp,
	_ProbeFeatureLowerName[9:15]:    ProbeFeatureIsapnp,
	_ProbeFeatureName[15:18]:        ProbeFeatureNet,
	_ProbeFeatureLowerName[15:18]:   ProbeFeatureNet,
	_ProbeFeatureName[18:24]:        ProbeFeatureFloppy,
	_ProbeFeatureLowerName[18:24]:   ProbeFeatureFloppy,
	_ProbeFeatureName[24:28]:        ProbeFeatureMisc,
	_ProbeFeatureLowerName[24:28]:   ProbeFeatureMisc,
	_ProbeFeatureName[28:38]:        ProbeFeatureMiscSerial,
	_ProbeFeatureLowerName[28:38]:   ProbeFeatureMiscSerial,
	_ProbeFeatureName[38:45]:        ProbeFeatureMiscPar,
	_ProbeFeatureLowerName[38:45]:   ProbeFeatureMiscPar,
	_ProbeFeatureName[45:55]:        ProbeFeatureMiscFloppy,
	_ProbeFeatureLowerName[45:55]:   ProbeFeatureMiscFloppy,
	_ProbeFeatureName[55:61]:        ProbeFeatureSerial,
	_ProbeFeatureLowerName[55:61]:   ProbeFeatureSerial,
	_ProbeFeatureName[61:64]:        ProbeFeatureCpu,
	_ProbeFeatureLowerName[61:64]:   ProbeFeatureCpu,
	_ProbeFeatureName[64:68]:        ProbeFeatureBios,
	_ProbeFeatureLowerName[64:68]:   ProbeFeatureBios,
	_ProbeFeatureName[68:75]:        ProbeFeatureMonitor,
	_ProbeFeatureLowerName[68:75]:   ProbeFeatureMonitor,
	_ProbeFeatureName[75:80]:        ProbeFeatureMouse,
	_ProbeFeatureLowerName[75:80]:   ProbeFeatureMouse,
	_ProbeFeatureName[80:84]:        ProbeFeatureScsi,
	_ProbeFeatureLowerName[80:84]:   ProbeFeatureScsi,
	_ProbeFeatureName[84:87]:        ProbeFeatureUsb,
	_ProbeFeatureLowerName[84:87]:   ProbeFeatureUsb,
	_ProbeFeatureName[87:94]:        ProbeFeatureUsbMods,
	_ProbeFeatureLowerName[87:94]:   ProbeFeatureUsbMods,
	_ProbeFeatureName[94:97]:        ProbeFeatureAdb,
	_ProbeFeatureLowerName[94:97]:   ProbeFeatureAdb,
	_ProbeFeatureName[97:102]:       ProbeFeatureModem,
	_ProbeFeatureLowerName[97:102]:  ProbeFeatureModem,
	_ProbeFeatureName[102:110]:      ProbeFeatureModemUsb,
	_ProbeFeatureLowerName[102:110]: ProbeFeatureModemUsb,
	_ProbeFeatureName[110:118]:      ProbeFeatureParallel,
	_ProbeFeatureLowerName[110:118]: ProbeFeatureParallel,
	_ProbeFeatureName[118:128]:      ProbeFeatureParallelLp,
	_ProbeFeatureLowerName[118:128]: ProbeFeatureParallelLp,
	_ProbeFeatureName[128:139]:      ProbeFeatureParallelZip,
	_ProbeFeatureLowerName[128:139]: ProbeFeatureParallelZip,
	_ProbeFeatureName[139:142]:      ProbeFeatureIsa,
	_ProbeFeatureLowerName[139:142]: ProbeFeatureIsa,
	_ProbeFeatureName[142:149]:      ProbeFeatureIsaIsdn,
	_ProbeFeatureLowerName[142:149]: ProbeFeatureIsaIsdn,
	_ProbeFeatureName[149:153]:      ProbeFeatureIsdn,
	_ProbeFeatureLowerName[149:153]: ProbeFeatureIsdn,
	_ProbeFeatureName[153:156]:      ProbeFeatureKbd,
	_ProbeFeatureLowerName[153:156]: ProbeFeatureKbd,
	_ProbeFeatureName[156:160]:      ProbeFeatureProm,
	_ProbeFeatureLowerName[156:160]: ProbeFeatureProm,
	_ProbeFeatureName[160:164]:      ProbeFeatureSbus,
	_ProbeFeatureLowerName[160:164]: ProbeFeatureSbus,
	_ProbeFeatureName[164:167]:      ProbeFeatureInt,
	_ProbeFeatureLowerName[164:167]: ProbeFeatureInt,
	_ProbeFeatureName[167:174]:      ProbeFeatureBraille,
	_ProbeFeatureLowerName[167:174]: ProbeFeatureBraille,
	_ProbeFeatureName[174:185]:      ProbeFeatureBrailleAlva,
	_ProbeFeatureLowerName[174:185]: ProbeFeatureBrailleAlva,
	_ProbeFeatureName[185:195]:      ProbeFeatureBrailleFhp,
	_ProbeFeatureLowerName[185:195]: ProbeFeatureBrailleFhp,
	_ProbeFeatureName[195:204]:      ProbeFeatureBrailleHt,
	_ProbeFeatureLowerName[195:204]: ProbeFeatureBrailleHt,
	_ProbeFeatureName[204:210]:      ProbeFeatureIgnx11,
	_ProbeFeatureLowerName[204:210]: ProbeFeatureIgnx11,
	_ProbeFeatureName[210:213]:      ProbeFeatureSys,
	_ProbeFeatureLowerName[210:213]: ProbeFeatureSys,
	_ProbeFeatureName[213:220]:      ProbeFeatureBiosVbe,
	_ProbeFeatureLowerName[213:220]: ProbeFeatureBiosVbe,
	_ProbeFeatureName[220:229]:      ProbeFeatureIsapnpOld,
	_ProbeFeatureLowerName[220:229]: ProbeFeatureIsapnpOld,
	_ProbeFeatureName[229:238]:      ProbeFeatureIsapnpNew,
	_ProbeFeatureLowerName[229:238]: ProbeFeatureIsapnpNew,
	_ProbeFeatureName[238:247]:      ProbeFeatureIsapnpMod,
	_ProbeFeatureLowerName[238:247]: ProbeFeatureIsapnpMod,
	_ProbeFeatureName[247:258]:      ProbeFeatureBrailleBaum,
	_ProbeFeatureLowerName[247:258]: ProbeFeatureBrailleBaum,
	_ProbeFeatureName[258:264]:      ProbeFeatureManual,
	_ProbeFeatureLowerName[258:264]: ProbeFeatureManual,
	_ProbeFeatureName[264:266]:      ProbeFeatureFb,
	_ProbeFeatureLowerName[264:266]: ProbeFeatureFb,
	_ProbeFeatureName[266:270]:      ProbeFeatureVeth,
	_ProbeFeatureLowerName[266:270]: ProbeFeatureVeth,
	_ProbeFeatureName[270:275]:      ProbeFeaturePppoe,
	_ProbeFeatureLowerName[270:275]: ProbeFeaturePppoe,
	_ProbeFeatureName[275:279]:      ProbeFeatureScan,
	_ProbeFeatureLowerName[275:279]: ProbeFeatureScan,
	_ProbeFeatureName[279:285]:      ProbeFeaturePcmcia,
	_ProbeFeatureLowerName[279:285]: ProbeFeaturePcmcia,
	_ProbeFeatureName[285:289]:      ProbeFeatureFork,
	_ProbeFeatureLowerName[285:289]: ProbeFeatureFork,
	_ProbeFeatureName[289:300]:      ProbeFeatureParallelImm,
	_ProbeFeatureLowerName[289:300]: ProbeFeatureParallelImm,
	_ProbeFeatureName[300:304]:      ProbeFeatureS390,
	_ProbeFeatureLowerName[300:304]: ProbeFeatureS390,
	_ProbeFeatureName[304:310]:      ProbeFeatureCpuemu,
	_ProbeFeatureLowerName[304:310]: ProbeFeatureCpuemu,
	_ProbeFeatureName[310:315]:      ProbeFeatureSysfs,
	_ProbeFeatureLowerName[310:315]: ProbeFeatureSysfs,
	_ProbeFeatureName[315:324]:      ProbeFeatureS390disks,
	_ProbeFeatureLowerName[315:324]: ProbeFeatureS390disks,
	_ProbeFeatureName[324:328]:      ProbeFeatureUdev,
	_ProbeFeatureLowerName[324:328]: ProbeFeatureUdev,
	_ProbeFeatureName[328:333]:      ProbeFeatureBlock,
	_ProbeFeatureLowerName[328:333]: ProbeFeatureBlock,
	_ProbeFeatureName[333:343]:      ProbeFeatureBlockCdrom,
	_ProbeFeatureLowerName[333:343]: ProbeFeatureBlockCdrom,
	_ProbeFeatureName[343:352]:      ProbeFeatureBlockPart,
	_ProbeFeatureLowerName[343:352]: ProbeFeatureBlockPart,
	_ProbeFeatureName[352:355]:      ProbeFeatureEdd,
	_ProbeFeatureLowerName[352:355]: ProbeFeatureEdd,
	_ProbeFeatureName[355:361]:      ProbeFeatureEddMod,
	_ProbeFeatureLowerName[355:361]: ProbeFeatureEddMod,
	_ProbeFeatureName[361:368]:      ProbeFeatureBiosDdc,
	_ProbeFeatureLowerName[361:368]: ProbeFeatureBiosDdc,
	_ProbeFeatureName[368:374]:      ProbeFeatureBiosFb,
	_ProbeFeatureLowerName[368:374]: ProbeFeatureBiosFb,
	_ProbeFeatureName[374:382]:      ProbeFeatureBiosMode,
	_ProbeFeatureLowerName[374:382]: ProbeFeatureBiosMode,
	_ProbeFeatureName[382:387]:      ProbeFeatureInput,
	_ProbeFeatureLowerName[382:387]: ProbeFeatureInput,
	_ProbeFeatureName[387:396]:      ProbeFeatureBlockMods,
	_ProbeFeatureLowerName[387:396]: ProbeFeatureBlockMods,
	_ProbeFeatureName[396:404]:      ProbeFeatureBiosVesa,
	_ProbeFeatureLowerName[396:404]: ProbeFeatureBiosVesa,
	_ProbeFeatureName[404:415]:      ProbeFeatureCpuemuDebug,
	_ProbeFeatureLowerName[404:415]: ProbeFeatureCpuemuDebug,
	_ProbeFeatureName[415:427]:      ProbeFeatureScsiNoserial,
	_ProbeFeatureLowerName[415:427]: ProbeFeatureScsiNoserial,
	_ProbeFeatureName[427:431]:      ProbeFeatureWlan,
	_ProbeFeatureLowerName[427:431]: ProbeFeatureWlan,
	_ProbeFeatureName[431:438]:      ProbeFeatureBiosCrc,
	_ProbeFeatureLowerName[431:438]: ProbeFeatureBiosCrc,
	_ProbeFeatureName[438:441]:      ProbeFeatureHal,
	_ProbeFeatureLowerName[438:441]: ProbeFeatureHal,
	_ProbeFeatureName[441:449]:      ProbeFeatureBiosVram,
	_ProbeFeatureLowerName[441:449]: ProbeFeatureBiosVram,
	_ProbeFeatureName[449:457]:      ProbeFeatureBiosAcpi,
	_ProbeFeatureLowerName[449:457]: ProbeFeatureBiosAcpi,
	_ProbeFeatureName[457:469]:      ProbeFeatureBiosDdcPorts,
	_ProbeFeatureLowerName[457:469]: ProbeFeatureBiosDdcPorts,
	_ProbeFeatureName[469:480]:      ProbeFeatureModulesPata,
	_ProbeFeatureLowerName[469:480]: ProbeFeatureModulesPata,
	_ProbeFeatureName[480:489]:      ProbeFeatureNetEeprom,
	_ProbeFeatureLowerName[480:489]: ProbeFeatureNetEeprom,
	_ProbeFeatureName[489:495]:      ProbeFeatureX86emu,
	_ProbeFeatureLowerName[489:495]: ProbeFeatureX86emu,
	_ProbeFeatureName[495:498]:      ProbeFeatureMax,
	_ProbeFeatureLowerName[495:498]: ProbeFeatureMax,
	_ProbeFeatureName[498:502]:      ProbeFeatureLxrc,
	_ProbeFeatureLowerName[498:502]: ProbeFeatureLxrc,
	_ProbeFeatureName[502:509]:      ProbeFeatureDefault,
	_ProbeFeatureLowerName[502:509]: ProbeFeatureDefault,
	_ProbeFeatureName[509:512]:      ProbeFeatureAll,
	_ProbeFeatureLowerName[509:512]: ProbeFeatureAll,
}

var _ProbeFeatureNames = []string{
	_ProbeFeatureName[0:6],
	_ProbeFeatureName[6:9],
	_ProbeFeatureName[9:15],
	_ProbeFeatureName[15:18],
	_ProbeFeatureName[18:24],
	_ProbeFeatureName[24:28],
	_ProbeFeatureName[28:38],
	_ProbeFeatureName[38:45],
	_ProbeFeatureName[45:55],
	_ProbeFeatureName[55:61],
	_ProbeFeatureName[61:64],
	_ProbeFeatureName[64:68],
	_ProbeFeatureName[68:75],
	_ProbeFeatureName[75:80],
	_ProbeFeatureName[80:84],
	_ProbeFeatureName[84:87],
	_ProbeFeatureName[87:94],
	_ProbeFeatureName[94:97],
	_ProbeFeatureName[97:102],
	_ProbeFeatureName[102:110],
	_ProbeFeatureName[110:118],
	_ProbeFeatureName[118:128],
	_ProbeFeatureName[128:139],
	_ProbeFeatureName[139:142],
	_ProbeFeatureName[142:149],
	_ProbeFeatureName[149:153],
	_ProbeFeatureName[153:156],
	_ProbeFeatureName[156:160],
	_ProbeFeatureName[160:164],
	_ProbeFeatureName[164:167],
	_ProbeFeatureName[167:174],
	_ProbeFeatureName[174:185],
	_ProbeFeatureName[185:195],
	_ProbeFeatureName[195:204],
	_ProbeFeatureName[204:210],
	_ProbeFeatureName[210:213],
	_ProbeFeatureName[213:220],
	_ProbeFeatureName[220:229],
	_ProbeFeatureName[229:238],
	_ProbeFeatureName[238:247],
	_ProbeFeatureName[247:258],
	_ProbeFeatureName[258:264],
	_ProbeFeatureName[264:266],
	_ProbeFeatureName[266:270],
	_ProbeFeatureName[270:275],
	_ProbeFeatureName[275:279],
	_ProbeFeatureName[279:285],
	_ProbeFeatureName[285:289],
	_ProbeFeatureName[289:300],
	_ProbeFeatureName[300:304],
	_ProbeFeatureName[304:310],
	_ProbeFeatureName[310:315],
	_ProbeFeatureName[315:324],
	_ProbeFeatureName[324:328],
	_ProbeFeatureName[328:333],
	_ProbeFeatureName[333:343],
	_ProbeFeatureName[343:352],
	_ProbeFeatureName[352:355],
	_ProbeFeatureName[355:361],
	_ProbeFeatureName[361:368],
	_ProbeFeatureName[368:374],
	_ProbeFeatureName[374:382],
	_ProbeFeatureName[382:387],
	_ProbeFeatureName[387:396],
	_ProbeFeatureName[396:404],
	_ProbeFeatureName[404:415],
	_ProbeFeatureName[415:427],
	_ProbeFeatureName[427:431],
	_ProbeFeatureName[431:438],
	_ProbeFeatureName[438:441],
	_ProbeFeatureName[441:449],
	_ProbeFeatureName[449:457],
	_ProbeFeatureName[457:469],
	_ProbeFeatureName[469:480],
	_ProbeFeatureName[480:489],
	_ProbeFeatureName[489:495],
	_ProbeFeatureName[495:498],
	_ProbeFeatureName[498:502],
	_ProbeFeatureName[502:509],
	_ProbeFeatureName[509:512],
}

// ProbeFeatureString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ProbeFeatureString(s string) (ProbeFeature, error) {
	if val, ok := _ProbeFeatureNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ProbeFeatureNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ProbeFeature values", s)
}

// ProbeFeatureValues returns all values of the enum
func ProbeFeatureValues() []ProbeFeature {
	return _ProbeFeatureValues
}

// ProbeFeatureStrings returns a slice of all String values of the enum
func ProbeFeatureStrings() []string {
	strs := make([]string, len(_ProbeFeatureNames))
	copy(strs, _ProbeFeatureNames)
	return strs
}

// IsAProbeFeature returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ProbeFeature) IsAProbeFeature() bool {
	for _, v := range _ProbeFeatureValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ProbeFeature
func (i ProbeFeature) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ProbeFeature
func (i *ProbeFeature) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ProbeFeature should be a string, got %s", data)
	}

	var err error
	*i, err = ProbeFeatureString(s)
	return err
}
