// Code generated by "enumer -type=ProbeFeature"; DO NOT EDIT.

package hwinfo

import (
	"fmt"
	"strings"
)

const _ProbeFeatureName = "ProbeFeatureMemoryProbeFeaturePciProbeFeatureIsapnpProbeFeatureNetProbeFeatureFloppyProbeFeatureMiscProbeFeatureMiscSerialProbeFeatureMiscParProbeFeatureMiscFloppyProbeFeatureSerialProbeFeatureCpuProbeFeatureBiosProbeFeatureMonitorProbeFeatureMouseProbeFeatureScsiProbeFeatureUsbProbeFeatureUsbModsProbeFeatureAdbProbeFeatureModemProbeFeatureModemUsbProbeFeatureParallelProbeFeatureParallelLpProbeFeatureParallelZipProbeFeatureIsaProbeFeatureIsaIsdnProbeFeatureIsdnProbeFeatureKbdProbeFeaturePromProbeFeatureSbusProbeFeatureIntProbeFeatureBrailleProbeFeatureBrailleAlvaProbeFeatureBrailleFhpProbeFeatureBrailleHtProbeFeatureIgnx11ProbeFeatureSysProbeFeatureBiosVbeProbeFeatureIsapnpOldProbeFeatureIsapnpNewProbeFeatureIsapnpModProbeFeatureBrailleBaumProbeFeatureManualProbeFeatureFbProbeFeatureVethProbeFeaturePppoeProbeFeatureScanProbeFeaturePcmciaProbeFeatureForkProbeFeatureParallelImmProbeFeatureS390ProbeFeatureCpuemuProbeFeatureSysfsProbeFeatureS390disksProbeFeatureUdevProbeFeatureBlockProbeFeatureBlockCdromProbeFeatureBlockPartProbeFeatureEddProbeFeatureEddModProbeFeatureBiosDdcProbeFeatureBiosFbProbeFeatureBiosModeProbeFeatureInputProbeFeatureBlockModsProbeFeatureBiosVesaProbeFeatureCpuemuDebugProbeFeatureScsiNoserialProbeFeatureWlanProbeFeatureBiosCrcProbeFeatureHalProbeFeatureBiosVramProbeFeatureBiosAcpiProbeFeatureBiosDdcPortsProbeFeatureModulesPataProbeFeatureNetEepromProbeFeatureX86emuProbeFeatureMaxProbeFeatureLxrcProbeFeatureDefaultProbeFeatureAll"

var _ProbeFeatureIndex = [...]uint16{0, 18, 33, 51, 66, 84, 100, 122, 141, 163, 181, 196, 212, 231, 248, 264, 279, 298, 313, 330, 350, 370, 392, 415, 430, 449, 465, 480, 496, 512, 527, 546, 569, 591, 612, 630, 645, 664, 685, 706, 727, 750, 768, 782, 798, 815, 831, 849, 865, 888, 904, 922, 939, 960, 976, 993, 1015, 1036, 1051, 1069, 1088, 1106, 1126, 1143, 1164, 1184, 1207, 1231, 1247, 1266, 1281, 1301, 1321, 1345, 1368, 1389, 1407, 1422, 1438, 1457, 1472}

const _ProbeFeatureLowerName = "probefeaturememoryprobefeaturepciprobefeatureisapnpprobefeaturenetprobefeaturefloppyprobefeaturemiscprobefeaturemiscserialprobefeaturemiscparprobefeaturemiscfloppyprobefeatureserialprobefeaturecpuprobefeaturebiosprobefeaturemonitorprobefeaturemouseprobefeaturescsiprobefeatureusbprobefeatureusbmodsprobefeatureadbprobefeaturemodemprobefeaturemodemusbprobefeatureparallelprobefeatureparallellpprobefeatureparallelzipprobefeatureisaprobefeatureisaisdnprobefeatureisdnprobefeaturekbdprobefeaturepromprobefeaturesbusprobefeatureintprobefeaturebrailleprobefeaturebraillealvaprobefeaturebraillefhpprobefeaturebraillehtprobefeatureignx11probefeaturesysprobefeaturebiosvbeprobefeatureisapnpoldprobefeatureisapnpnewprobefeatureisapnpmodprobefeaturebraillebaumprobefeaturemanualprobefeaturefbprobefeaturevethprobefeaturepppoeprobefeaturescanprobefeaturepcmciaprobefeatureforkprobefeatureparallelimmprobefeatures390probefeaturecpuemuprobefeaturesysfsprobefeatures390disksprobefeatureudevprobefeatureblockprobefeatureblockcdromprobefeatureblockpartprobefeatureeddprobefeatureeddmodprobefeaturebiosddcprobefeaturebiosfbprobefeaturebiosmodeprobefeatureinputprobefeatureblockmodsprobefeaturebiosvesaprobefeaturecpuemudebugprobefeaturescsinoserialprobefeaturewlanprobefeaturebioscrcprobefeaturehalprobefeaturebiosvramprobefeaturebiosacpiprobefeaturebiosddcportsprobefeaturemodulespataprobefeatureneteepromprobefeaturex86emuprobefeaturemaxprobefeaturelxrcprobefeaturedefaultprobefeatureall"

func (i ProbeFeature) String() string {
	i -= 1
	if i < 0 || i >= ProbeFeature(len(_ProbeFeatureIndex)-1) {
		return fmt.Sprintf("ProbeFeature(%d)", i+1)
	}
	return _ProbeFeatureName[_ProbeFeatureIndex[i]:_ProbeFeatureIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ProbeFeatureNoOp() {
	var x [1]struct{}
	_ = x[ProbeFeatureMemory-(1)]
	_ = x[ProbeFeaturePci-(2)]
	_ = x[ProbeFeatureIsapnp-(3)]
	_ = x[ProbeFeatureNet-(4)]
	_ = x[ProbeFeatureFloppy-(5)]
	_ = x[ProbeFeatureMisc-(6)]
	_ = x[ProbeFeatureMiscSerial-(7)]
	_ = x[ProbeFeatureMiscPar-(8)]
	_ = x[ProbeFeatureMiscFloppy-(9)]
	_ = x[ProbeFeatureSerial-(10)]
	_ = x[ProbeFeatureCpu-(11)]
	_ = x[ProbeFeatureBios-(12)]
	_ = x[ProbeFeatureMonitor-(13)]
	_ = x[ProbeFeatureMouse-(14)]
	_ = x[ProbeFeatureScsi-(15)]
	_ = x[ProbeFeatureUsb-(16)]
	_ = x[ProbeFeatureUsbMods-(17)]
	_ = x[ProbeFeatureAdb-(18)]
	_ = x[ProbeFeatureModem-(19)]
	_ = x[ProbeFeatureModemUsb-(20)]
	_ = x[ProbeFeatureParallel-(21)]
	_ = x[ProbeFeatureParallelLp-(22)]
	_ = x[ProbeFeatureParallelZip-(23)]
	_ = x[ProbeFeatureIsa-(24)]
	_ = x[ProbeFeatureIsaIsdn-(25)]
	_ = x[ProbeFeatureIsdn-(26)]
	_ = x[ProbeFeatureKbd-(27)]
	_ = x[ProbeFeatureProm-(28)]
	_ = x[ProbeFeatureSbus-(29)]
	_ = x[ProbeFeatureInt-(30)]
	_ = x[ProbeFeatureBraille-(31)]
	_ = x[ProbeFeatureBrailleAlva-(32)]
	_ = x[ProbeFeatureBrailleFhp-(33)]
	_ = x[ProbeFeatureBrailleHt-(34)]
	_ = x[ProbeFeatureIgnx11-(35)]
	_ = x[ProbeFeatureSys-(36)]
	_ = x[ProbeFeatureBiosVbe-(37)]
	_ = x[ProbeFeatureIsapnpOld-(38)]
	_ = x[ProbeFeatureIsapnpNew-(39)]
	_ = x[ProbeFeatureIsapnpMod-(40)]
	_ = x[ProbeFeatureBrailleBaum-(41)]
	_ = x[ProbeFeatureManual-(42)]
	_ = x[ProbeFeatureFb-(43)]
	_ = x[ProbeFeatureVeth-(44)]
	_ = x[ProbeFeaturePppoe-(45)]
	_ = x[ProbeFeatureScan-(46)]
	_ = x[ProbeFeaturePcmcia-(47)]
	_ = x[ProbeFeatureFork-(48)]
	_ = x[ProbeFeatureParallelImm-(49)]
	_ = x[ProbeFeatureS390-(50)]
	_ = x[ProbeFeatureCpuemu-(51)]
	_ = x[ProbeFeatureSysfs-(52)]
	_ = x[ProbeFeatureS390disks-(53)]
	_ = x[ProbeFeatureUdev-(54)]
	_ = x[ProbeFeatureBlock-(55)]
	_ = x[ProbeFeatureBlockCdrom-(56)]
	_ = x[ProbeFeatureBlockPart-(57)]
	_ = x[ProbeFeatureEdd-(58)]
	_ = x[ProbeFeatureEddMod-(59)]
	_ = x[ProbeFeatureBiosDdc-(60)]
	_ = x[ProbeFeatureBiosFb-(61)]
	_ = x[ProbeFeatureBiosMode-(62)]
	_ = x[ProbeFeatureInput-(63)]
	_ = x[ProbeFeatureBlockMods-(64)]
	_ = x[ProbeFeatureBiosVesa-(65)]
	_ = x[ProbeFeatureCpuemuDebug-(66)]
	_ = x[ProbeFeatureScsiNoserial-(67)]
	_ = x[ProbeFeatureWlan-(68)]
	_ = x[ProbeFeatureBiosCrc-(69)]
	_ = x[ProbeFeatureHal-(70)]
	_ = x[ProbeFeatureBiosVram-(71)]
	_ = x[ProbeFeatureBiosAcpi-(72)]
	_ = x[ProbeFeatureBiosDdcPorts-(73)]
	_ = x[ProbeFeatureModulesPata-(74)]
	_ = x[ProbeFeatureNetEeprom-(75)]
	_ = x[ProbeFeatureX86emu-(76)]
	_ = x[ProbeFeatureMax-(77)]
	_ = x[ProbeFeatureLxrc-(78)]
	_ = x[ProbeFeatureDefault-(79)]
	_ = x[ProbeFeatureAll-(80)]
}

var _ProbeFeatureValues = []ProbeFeature{ProbeFeatureMemory, ProbeFeaturePci, ProbeFeatureIsapnp, ProbeFeatureNet, ProbeFeatureFloppy, ProbeFeatureMisc, ProbeFeatureMiscSerial, ProbeFeatureMiscPar, ProbeFeatureMiscFloppy, ProbeFeatureSerial, ProbeFeatureCpu, ProbeFeatureBios, ProbeFeatureMonitor, ProbeFeatureMouse, ProbeFeatureScsi, ProbeFeatureUsb, ProbeFeatureUsbMods, ProbeFeatureAdb, ProbeFeatureModem, ProbeFeatureModemUsb, ProbeFeatureParallel, ProbeFeatureParallelLp, ProbeFeatureParallelZip, ProbeFeatureIsa, ProbeFeatureIsaIsdn, ProbeFeatureIsdn, ProbeFeatureKbd, ProbeFeatureProm, ProbeFeatureSbus, ProbeFeatureInt, ProbeFeatureBraille, ProbeFeatureBrailleAlva, ProbeFeatureBrailleFhp, ProbeFeatureBrailleHt, ProbeFeatureIgnx11, ProbeFeatureSys, ProbeFeatureBiosVbe, ProbeFeatureIsapnpOld, ProbeFeatureIsapnpNew, ProbeFeatureIsapnpMod, ProbeFeatureBrailleBaum, ProbeFeatureManual, ProbeFeatureFb, ProbeFeatureVeth, ProbeFeaturePppoe, ProbeFeatureScan, ProbeFeaturePcmcia, ProbeFeatureFork, ProbeFeatureParallelImm, ProbeFeatureS390, ProbeFeatureCpuemu, ProbeFeatureSysfs, ProbeFeatureS390disks, ProbeFeatureUdev, ProbeFeatureBlock, ProbeFeatureBlockCdrom, ProbeFeatureBlockPart, ProbeFeatureEdd, ProbeFeatureEddMod, ProbeFeatureBiosDdc, ProbeFeatureBiosFb, ProbeFeatureBiosMode, ProbeFeatureInput, ProbeFeatureBlockMods, ProbeFeatureBiosVesa, ProbeFeatureCpuemuDebug, ProbeFeatureScsiNoserial, ProbeFeatureWlan, ProbeFeatureBiosCrc, ProbeFeatureHal, ProbeFeatureBiosVram, ProbeFeatureBiosAcpi, ProbeFeatureBiosDdcPorts, ProbeFeatureModulesPata, ProbeFeatureNetEeprom, ProbeFeatureX86emu, ProbeFeatureMax, ProbeFeatureLxrc, ProbeFeatureDefault, ProbeFeatureAll}

var _ProbeFeatureNameToValueMap = map[string]ProbeFeature{
	_ProbeFeatureName[0:18]:           ProbeFeatureMemory,
	_ProbeFeatureLowerName[0:18]:      ProbeFeatureMemory,
	_ProbeFeatureName[18:33]:          ProbeFeaturePci,
	_ProbeFeatureLowerName[18:33]:     ProbeFeaturePci,
	_ProbeFeatureName[33:51]:          ProbeFeatureIsapnp,
	_ProbeFeatureLowerName[33:51]:     ProbeFeatureIsapnp,
	_ProbeFeatureName[51:66]:          ProbeFeatureNet,
	_ProbeFeatureLowerName[51:66]:     ProbeFeatureNet,
	_ProbeFeatureName[66:84]:          ProbeFeatureFloppy,
	_ProbeFeatureLowerName[66:84]:     ProbeFeatureFloppy,
	_ProbeFeatureName[84:100]:         ProbeFeatureMisc,
	_ProbeFeatureLowerName[84:100]:    ProbeFeatureMisc,
	_ProbeFeatureName[100:122]:        ProbeFeatureMiscSerial,
	_ProbeFeatureLowerName[100:122]:   ProbeFeatureMiscSerial,
	_ProbeFeatureName[122:141]:        ProbeFeatureMiscPar,
	_ProbeFeatureLowerName[122:141]:   ProbeFeatureMiscPar,
	_ProbeFeatureName[141:163]:        ProbeFeatureMiscFloppy,
	_ProbeFeatureLowerName[141:163]:   ProbeFeatureMiscFloppy,
	_ProbeFeatureName[163:181]:        ProbeFeatureSerial,
	_ProbeFeatureLowerName[163:181]:   ProbeFeatureSerial,
	_ProbeFeatureName[181:196]:        ProbeFeatureCpu,
	_ProbeFeatureLowerName[181:196]:   ProbeFeatureCpu,
	_ProbeFeatureName[196:212]:        ProbeFeatureBios,
	_ProbeFeatureLowerName[196:212]:   ProbeFeatureBios,
	_ProbeFeatureName[212:231]:        ProbeFeatureMonitor,
	_ProbeFeatureLowerName[212:231]:   ProbeFeatureMonitor,
	_ProbeFeatureName[231:248]:        ProbeFeatureMouse,
	_ProbeFeatureLowerName[231:248]:   ProbeFeatureMouse,
	_ProbeFeatureName[248:264]:        ProbeFeatureScsi,
	_ProbeFeatureLowerName[248:264]:   ProbeFeatureScsi,
	_ProbeFeatureName[264:279]:        ProbeFeatureUsb,
	_ProbeFeatureLowerName[264:279]:   ProbeFeatureUsb,
	_ProbeFeatureName[279:298]:        ProbeFeatureUsbMods,
	_ProbeFeatureLowerName[279:298]:   ProbeFeatureUsbMods,
	_ProbeFeatureName[298:313]:        ProbeFeatureAdb,
	_ProbeFeatureLowerName[298:313]:   ProbeFeatureAdb,
	_ProbeFeatureName[313:330]:        ProbeFeatureModem,
	_ProbeFeatureLowerName[313:330]:   ProbeFeatureModem,
	_ProbeFeatureName[330:350]:        ProbeFeatureModemUsb,
	_ProbeFeatureLowerName[330:350]:   ProbeFeatureModemUsb,
	_ProbeFeatureName[350:370]:        ProbeFeatureParallel,
	_ProbeFeatureLowerName[350:370]:   ProbeFeatureParallel,
	_ProbeFeatureName[370:392]:        ProbeFeatureParallelLp,
	_ProbeFeatureLowerName[370:392]:   ProbeFeatureParallelLp,
	_ProbeFeatureName[392:415]:        ProbeFeatureParallelZip,
	_ProbeFeatureLowerName[392:415]:   ProbeFeatureParallelZip,
	_ProbeFeatureName[415:430]:        ProbeFeatureIsa,
	_ProbeFeatureLowerName[415:430]:   ProbeFeatureIsa,
	_ProbeFeatureName[430:449]:        ProbeFeatureIsaIsdn,
	_ProbeFeatureLowerName[430:449]:   ProbeFeatureIsaIsdn,
	_ProbeFeatureName[449:465]:        ProbeFeatureIsdn,
	_ProbeFeatureLowerName[449:465]:   ProbeFeatureIsdn,
	_ProbeFeatureName[465:480]:        ProbeFeatureKbd,
	_ProbeFeatureLowerName[465:480]:   ProbeFeatureKbd,
	_ProbeFeatureName[480:496]:        ProbeFeatureProm,
	_ProbeFeatureLowerName[480:496]:   ProbeFeatureProm,
	_ProbeFeatureName[496:512]:        ProbeFeatureSbus,
	_ProbeFeatureLowerName[496:512]:   ProbeFeatureSbus,
	_ProbeFeatureName[512:527]:        ProbeFeatureInt,
	_ProbeFeatureLowerName[512:527]:   ProbeFeatureInt,
	_ProbeFeatureName[527:546]:        ProbeFeatureBraille,
	_ProbeFeatureLowerName[527:546]:   ProbeFeatureBraille,
	_ProbeFeatureName[546:569]:        ProbeFeatureBrailleAlva,
	_ProbeFeatureLowerName[546:569]:   ProbeFeatureBrailleAlva,
	_ProbeFeatureName[569:591]:        ProbeFeatureBrailleFhp,
	_ProbeFeatureLowerName[569:591]:   ProbeFeatureBrailleFhp,
	_ProbeFeatureName[591:612]:        ProbeFeatureBrailleHt,
	_ProbeFeatureLowerName[591:612]:   ProbeFeatureBrailleHt,
	_ProbeFeatureName[612:630]:        ProbeFeatureIgnx11,
	_ProbeFeatureLowerName[612:630]:   ProbeFeatureIgnx11,
	_ProbeFeatureName[630:645]:        ProbeFeatureSys,
	_ProbeFeatureLowerName[630:645]:   ProbeFeatureSys,
	_ProbeFeatureName[645:664]:        ProbeFeatureBiosVbe,
	_ProbeFeatureLowerName[645:664]:   ProbeFeatureBiosVbe,
	_ProbeFeatureName[664:685]:        ProbeFeatureIsapnpOld,
	_ProbeFeatureLowerName[664:685]:   ProbeFeatureIsapnpOld,
	_ProbeFeatureName[685:706]:        ProbeFeatureIsapnpNew,
	_ProbeFeatureLowerName[685:706]:   ProbeFeatureIsapnpNew,
	_ProbeFeatureName[706:727]:        ProbeFeatureIsapnpMod,
	_ProbeFeatureLowerName[706:727]:   ProbeFeatureIsapnpMod,
	_ProbeFeatureName[727:750]:        ProbeFeatureBrailleBaum,
	_ProbeFeatureLowerName[727:750]:   ProbeFeatureBrailleBaum,
	_ProbeFeatureName[750:768]:        ProbeFeatureManual,
	_ProbeFeatureLowerName[750:768]:   ProbeFeatureManual,
	_ProbeFeatureName[768:782]:        ProbeFeatureFb,
	_ProbeFeatureLowerName[768:782]:   ProbeFeatureFb,
	_ProbeFeatureName[782:798]:        ProbeFeatureVeth,
	_ProbeFeatureLowerName[782:798]:   ProbeFeatureVeth,
	_ProbeFeatureName[798:815]:        ProbeFeaturePppoe,
	_ProbeFeatureLowerName[798:815]:   ProbeFeaturePppoe,
	_ProbeFeatureName[815:831]:        ProbeFeatureScan,
	_ProbeFeatureLowerName[815:831]:   ProbeFeatureScan,
	_ProbeFeatureName[831:849]:        ProbeFeaturePcmcia,
	_ProbeFeatureLowerName[831:849]:   ProbeFeaturePcmcia,
	_ProbeFeatureName[849:865]:        ProbeFeatureFork,
	_ProbeFeatureLowerName[849:865]:   ProbeFeatureFork,
	_ProbeFeatureName[865:888]:        ProbeFeatureParallelImm,
	_ProbeFeatureLowerName[865:888]:   ProbeFeatureParallelImm,
	_ProbeFeatureName[888:904]:        ProbeFeatureS390,
	_ProbeFeatureLowerName[888:904]:   ProbeFeatureS390,
	_ProbeFeatureName[904:922]:        ProbeFeatureCpuemu,
	_ProbeFeatureLowerName[904:922]:   ProbeFeatureCpuemu,
	_ProbeFeatureName[922:939]:        ProbeFeatureSysfs,
	_ProbeFeatureLowerName[922:939]:   ProbeFeatureSysfs,
	_ProbeFeatureName[939:960]:        ProbeFeatureS390disks,
	_ProbeFeatureLowerName[939:960]:   ProbeFeatureS390disks,
	_ProbeFeatureName[960:976]:        ProbeFeatureUdev,
	_ProbeFeatureLowerName[960:976]:   ProbeFeatureUdev,
	_ProbeFeatureName[976:993]:        ProbeFeatureBlock,
	_ProbeFeatureLowerName[976:993]:   ProbeFeatureBlock,
	_ProbeFeatureName[993:1015]:       ProbeFeatureBlockCdrom,
	_ProbeFeatureLowerName[993:1015]:  ProbeFeatureBlockCdrom,
	_ProbeFeatureName[1015:1036]:      ProbeFeatureBlockPart,
	_ProbeFeatureLowerName[1015:1036]: ProbeFeatureBlockPart,
	_ProbeFeatureName[1036:1051]:      ProbeFeatureEdd,
	_ProbeFeatureLowerName[1036:1051]: ProbeFeatureEdd,
	_ProbeFeatureName[1051:1069]:      ProbeFeatureEddMod,
	_ProbeFeatureLowerName[1051:1069]: ProbeFeatureEddMod,
	_ProbeFeatureName[1069:1088]:      ProbeFeatureBiosDdc,
	_ProbeFeatureLowerName[1069:1088]: ProbeFeatureBiosDdc,
	_ProbeFeatureName[1088:1106]:      ProbeFeatureBiosFb,
	_ProbeFeatureLowerName[1088:1106]: ProbeFeatureBiosFb,
	_ProbeFeatureName[1106:1126]:      ProbeFeatureBiosMode,
	_ProbeFeatureLowerName[1106:1126]: ProbeFeatureBiosMode,
	_ProbeFeatureName[1126:1143]:      ProbeFeatureInput,
	_ProbeFeatureLowerName[1126:1143]: ProbeFeatureInput,
	_ProbeFeatureName[1143:1164]:      ProbeFeatureBlockMods,
	_ProbeFeatureLowerName[1143:1164]: ProbeFeatureBlockMods,
	_ProbeFeatureName[1164:1184]:      ProbeFeatureBiosVesa,
	_ProbeFeatureLowerName[1164:1184]: ProbeFeatureBiosVesa,
	_ProbeFeatureName[1184:1207]:      ProbeFeatureCpuemuDebug,
	_ProbeFeatureLowerName[1184:1207]: ProbeFeatureCpuemuDebug,
	_ProbeFeatureName[1207:1231]:      ProbeFeatureScsiNoserial,
	_ProbeFeatureLowerName[1207:1231]: ProbeFeatureScsiNoserial,
	_ProbeFeatureName[1231:1247]:      ProbeFeatureWlan,
	_ProbeFeatureLowerName[1231:1247]: ProbeFeatureWlan,
	_ProbeFeatureName[1247:1266]:      ProbeFeatureBiosCrc,
	_ProbeFeatureLowerName[1247:1266]: ProbeFeatureBiosCrc,
	_ProbeFeatureName[1266:1281]:      ProbeFeatureHal,
	_ProbeFeatureLowerName[1266:1281]: ProbeFeatureHal,
	_ProbeFeatureName[1281:1301]:      ProbeFeatureBiosVram,
	_ProbeFeatureLowerName[1281:1301]: ProbeFeatureBiosVram,
	_ProbeFeatureName[1301:1321]:      ProbeFeatureBiosAcpi,
	_ProbeFeatureLowerName[1301:1321]: ProbeFeatureBiosAcpi,
	_ProbeFeatureName[1321:1345]:      ProbeFeatureBiosDdcPorts,
	_ProbeFeatureLowerName[1321:1345]: ProbeFeatureBiosDdcPorts,
	_ProbeFeatureName[1345:1368]:      ProbeFeatureModulesPata,
	_ProbeFeatureLowerName[1345:1368]: ProbeFeatureModulesPata,
	_ProbeFeatureName[1368:1389]:      ProbeFeatureNetEeprom,
	_ProbeFeatureLowerName[1368:1389]: ProbeFeatureNetEeprom,
	_ProbeFeatureName[1389:1407]:      ProbeFeatureX86emu,
	_ProbeFeatureLowerName[1389:1407]: ProbeFeatureX86emu,
	_ProbeFeatureName[1407:1422]:      ProbeFeatureMax,
	_ProbeFeatureLowerName[1407:1422]: ProbeFeatureMax,
	_ProbeFeatureName[1422:1438]:      ProbeFeatureLxrc,
	_ProbeFeatureLowerName[1422:1438]: ProbeFeatureLxrc,
	_ProbeFeatureName[1438:1457]:      ProbeFeatureDefault,
	_ProbeFeatureLowerName[1438:1457]: ProbeFeatureDefault,
	_ProbeFeatureName[1457:1472]:      ProbeFeatureAll,
	_ProbeFeatureLowerName[1457:1472]: ProbeFeatureAll,
}

var _ProbeFeatureNames = []string{
	_ProbeFeatureName[0:18],
	_ProbeFeatureName[18:33],
	_ProbeFeatureName[33:51],
	_ProbeFeatureName[51:66],
	_ProbeFeatureName[66:84],
	_ProbeFeatureName[84:100],
	_ProbeFeatureName[100:122],
	_ProbeFeatureName[122:141],
	_ProbeFeatureName[141:163],
	_ProbeFeatureName[163:181],
	_ProbeFeatureName[181:196],
	_ProbeFeatureName[196:212],
	_ProbeFeatureName[212:231],
	_ProbeFeatureName[231:248],
	_ProbeFeatureName[248:264],
	_ProbeFeatureName[264:279],
	_ProbeFeatureName[279:298],
	_ProbeFeatureName[298:313],
	_ProbeFeatureName[313:330],
	_ProbeFeatureName[330:350],
	_ProbeFeatureName[350:370],
	_ProbeFeatureName[370:392],
	_ProbeFeatureName[392:415],
	_ProbeFeatureName[415:430],
	_ProbeFeatureName[430:449],
	_ProbeFeatureName[449:465],
	_ProbeFeatureName[465:480],
	_ProbeFeatureName[480:496],
	_ProbeFeatureName[496:512],
	_ProbeFeatureName[512:527],
	_ProbeFeatureName[527:546],
	_ProbeFeatureName[546:569],
	_ProbeFeatureName[569:591],
	_ProbeFeatureName[591:612],
	_ProbeFeatureName[612:630],
	_ProbeFeatureName[630:645],
	_ProbeFeatureName[645:664],
	_ProbeFeatureName[664:685],
	_ProbeFeatureName[685:706],
	_ProbeFeatureName[706:727],
	_ProbeFeatureName[727:750],
	_ProbeFeatureName[750:768],
	_ProbeFeatureName[768:782],
	_ProbeFeatureName[782:798],
	_ProbeFeatureName[798:815],
	_ProbeFeatureName[815:831],
	_ProbeFeatureName[831:849],
	_ProbeFeatureName[849:865],
	_ProbeFeatureName[865:888],
	_ProbeFeatureName[888:904],
	_ProbeFeatureName[904:922],
	_ProbeFeatureName[922:939],
	_ProbeFeatureName[939:960],
	_ProbeFeatureName[960:976],
	_ProbeFeatureName[976:993],
	_ProbeFeatureName[993:1015],
	_ProbeFeatureName[1015:1036],
	_ProbeFeatureName[1036:1051],
	_ProbeFeatureName[1051:1069],
	_ProbeFeatureName[1069:1088],
	_ProbeFeatureName[1088:1106],
	_ProbeFeatureName[1106:1126],
	_ProbeFeatureName[1126:1143],
	_ProbeFeatureName[1143:1164],
	_ProbeFeatureName[1164:1184],
	_ProbeFeatureName[1184:1207],
	_ProbeFeatureName[1207:1231],
	_ProbeFeatureName[1231:1247],
	_ProbeFeatureName[1247:1266],
	_ProbeFeatureName[1266:1281],
	_ProbeFeatureName[1281:1301],
	_ProbeFeatureName[1301:1321],
	_ProbeFeatureName[1321:1345],
	_ProbeFeatureName[1345:1368],
	_ProbeFeatureName[1368:1389],
	_ProbeFeatureName[1389:1407],
	_ProbeFeatureName[1407:1422],
	_ProbeFeatureName[1422:1438],
	_ProbeFeatureName[1438:1457],
	_ProbeFeatureName[1457:1472],
}

// ProbeFeatureString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ProbeFeatureString(s string) (ProbeFeature, error) {
	if val, ok := _ProbeFeatureNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ProbeFeatureNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ProbeFeature values", s)
}

// ProbeFeatureValues returns all values of the enum
func ProbeFeatureValues() []ProbeFeature {
	return _ProbeFeatureValues
}

// ProbeFeatureStrings returns a slice of all String values of the enum
func ProbeFeatureStrings() []string {
	strs := make([]string, len(_ProbeFeatureNames))
	copy(strs, _ProbeFeatureNames)
	return strs
}

// IsAProbeFeature returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ProbeFeature) IsAProbeFeature() bool {
	for _, v := range _ProbeFeatureValues {
		if i == v {
			return true
		}
	}
	return false
}
