// Code generated by "enumer -type=ProbeFeature -json -transform=snake -trimprefix ProbeFeature -output=./report_enum_probe_feature.go"; DO NOT EDIT.

package hwinfo

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _ProbeFeatureName = "memorypciisapnpnetfloppymiscmisc_serialmisc_parmisc_floppyserialcpubiosmonitormousescsiusbusb_modsadbmodemmodem_usbparallelparallel_lpparallel_zipisaisa_isdnisdnkbdpromsbusintbraillebraille_alvabraille_fhpbraille_htignx11sysbios_vbeisapnp_oldisapnp_newisapnp_modbraille_baummanualfbvethpppoescanpcmciaforkparallel_imms390cpuemusysfss390disksudevblockblock_cdromblock_parteddedd_modbios_ddcbios_fbbios_modeinputblock_modsbios_vesacpuemu_debugscsi_noserialwlanbios_crchalbios_vrambios_acpibios_ddc_portsmodules_patanet_eepromx86emumaxlxrcdefaultall"

var _ProbeFeatureIndex = [...]uint16{0, 6, 9, 15, 18, 24, 28, 39, 47, 58, 64, 67, 71, 78, 83, 87, 90, 98, 101, 106, 115, 123, 134, 146, 149, 157, 161, 164, 168, 172, 175, 182, 194, 205, 215, 221, 224, 232, 242, 252, 262, 274, 280, 282, 286, 291, 295, 301, 305, 317, 321, 327, 332, 341, 345, 350, 361, 371, 374, 381, 389, 396, 405, 410, 420, 429, 441, 454, 458, 466, 469, 478, 487, 501, 513, 523, 529, 532, 536, 543, 546}

const _ProbeFeatureLowerName = "memorypciisapnpnetfloppymiscmisc_serialmisc_parmisc_floppyserialcpubiosmonitormousescsiusbusb_modsadbmodemmodem_usbparallelparallel_lpparallel_zipisaisa_isdnisdnkbdpromsbusintbraillebraille_alvabraille_fhpbraille_htignx11sysbios_vbeisapnp_oldisapnp_newisapnp_modbraille_baummanualfbvethpppoescanpcmciaforkparallel_imms390cpuemusysfss390disksudevblockblock_cdromblock_parteddedd_modbios_ddcbios_fbbios_modeinputblock_modsbios_vesacpuemu_debugscsi_noserialwlanbios_crchalbios_vrambios_acpibios_ddc_portsmodules_patanet_eepromx86emumaxlxrcdefaultall"

func (i ProbeFeature) String() string {
	i -= 1
	if i >= ProbeFeature(len(_ProbeFeatureIndex)-1) {
		return fmt.Sprintf("ProbeFeature(%d)", i+1)
	}
	return _ProbeFeatureName[_ProbeFeatureIndex[i]:_ProbeFeatureIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ProbeFeatureNoOp() {
	var x [1]struct{}
	_ = x[ProbeFeatureMemory-(1)]
	_ = x[ProbeFeaturePci-(2)]
	_ = x[ProbeFeatureIsapnp-(3)]
	_ = x[ProbeFeatureNet-(4)]
	_ = x[ProbeFeatureFloppy-(5)]
	_ = x[ProbeFeatureMisc-(6)]
	_ = x[ProbeFeatureMiscSerial-(7)]
	_ = x[ProbeFeatureMiscPar-(8)]
	_ = x[ProbeFeatureMiscFloppy-(9)]
	_ = x[ProbeFeatureSerial-(10)]
	_ = x[ProbeFeatureCpu-(11)]
	_ = x[ProbeFeatureBios-(12)]
	_ = x[ProbeFeatureMonitor-(13)]
	_ = x[ProbeFeatureMouse-(14)]
	_ = x[ProbeFeatureScsi-(15)]
	_ = x[ProbeFeatureUsb-(16)]
	_ = x[ProbeFeatureUsbMods-(17)]
	_ = x[ProbeFeatureAdb-(18)]
	_ = x[ProbeFeatureModem-(19)]
	_ = x[ProbeFeatureModemUsb-(20)]
	_ = x[ProbeFeatureParallel-(21)]
	_ = x[ProbeFeatureParallelLp-(22)]
	_ = x[ProbeFeatureParallelZip-(23)]
	_ = x[ProbeFeatureIsa-(24)]
	_ = x[ProbeFeatureIsaIsdn-(25)]
	_ = x[ProbeFeatureIsdn-(26)]
	_ = x[ProbeFeatureKbd-(27)]
	_ = x[ProbeFeatureProm-(28)]
	_ = x[ProbeFeatureSbus-(29)]
	_ = x[ProbeFeatureInt-(30)]
	_ = x[ProbeFeatureBraille-(31)]
	_ = x[ProbeFeatureBrailleAlva-(32)]
	_ = x[ProbeFeatureBrailleFhp-(33)]
	_ = x[ProbeFeatureBrailleHt-(34)]
	_ = x[ProbeFeatureIgnx11-(35)]
	_ = x[ProbeFeatureSys-(36)]
	_ = x[ProbeFeatureBiosVbe-(37)]
	_ = x[ProbeFeatureIsapnpOld-(38)]
	_ = x[ProbeFeatureIsapnpNew-(39)]
	_ = x[ProbeFeatureIsapnpMod-(40)]
	_ = x[ProbeFeatureBrailleBaum-(41)]
	_ = x[ProbeFeatureManual-(42)]
	_ = x[ProbeFeatureFb-(43)]
	_ = x[ProbeFeatureVeth-(44)]
	_ = x[ProbeFeaturePppoe-(45)]
	_ = x[ProbeFeatureScan-(46)]
	_ = x[ProbeFeaturePcmcia-(47)]
	_ = x[ProbeFeatureFork-(48)]
	_ = x[ProbeFeatureParallelImm-(49)]
	_ = x[ProbeFeatureS390-(50)]
	_ = x[ProbeFeatureCpuemu-(51)]
	_ = x[ProbeFeatureSysfs-(52)]
	_ = x[ProbeFeatureS390disks-(53)]
	_ = x[ProbeFeatureUdev-(54)]
	_ = x[ProbeFeatureBlock-(55)]
	_ = x[ProbeFeatureBlockCdrom-(56)]
	_ = x[ProbeFeatureBlockPart-(57)]
	_ = x[ProbeFeatureEdd-(58)]
	_ = x[ProbeFeatureEddMod-(59)]
	_ = x[ProbeFeatureBiosDdc-(60)]
	_ = x[ProbeFeatureBiosFb-(61)]
	_ = x[ProbeFeatureBiosMode-(62)]
	_ = x[ProbeFeatureInput-(63)]
	_ = x[ProbeFeatureBlockMods-(64)]
	_ = x[ProbeFeatureBiosVesa-(65)]
	_ = x[ProbeFeatureCpuemuDebug-(66)]
	_ = x[ProbeFeatureScsiNoserial-(67)]
	_ = x[ProbeFeatureWlan-(68)]
	_ = x[ProbeFeatureBiosCrc-(69)]
	_ = x[ProbeFeatureHal-(70)]
	_ = x[ProbeFeatureBiosVram-(71)]
	_ = x[ProbeFeatureBiosAcpi-(72)]
	_ = x[ProbeFeatureBiosDdcPorts-(73)]
	_ = x[ProbeFeatureModulesPata-(74)]
	_ = x[ProbeFeatureNetEeprom-(75)]
	_ = x[ProbeFeatureX86emu-(76)]
	_ = x[ProbeFeatureMax-(77)]
	_ = x[ProbeFeatureLxrc-(78)]
	_ = x[ProbeFeatureDefault-(79)]
	_ = x[ProbeFeatureAll-(80)]
}

var _ProbeFeatureValues = []ProbeFeature{ProbeFeatureMemory, ProbeFeaturePci, ProbeFeatureIsapnp, ProbeFeatureNet, ProbeFeatureFloppy, ProbeFeatureMisc, ProbeFeatureMiscSerial, ProbeFeatureMiscPar, ProbeFeatureMiscFloppy, ProbeFeatureSerial, ProbeFeatureCpu, ProbeFeatureBios, ProbeFeatureMonitor, ProbeFeatureMouse, ProbeFeatureScsi, ProbeFeatureUsb, ProbeFeatureUsbMods, ProbeFeatureAdb, ProbeFeatureModem, ProbeFeatureModemUsb, ProbeFeatureParallel, ProbeFeatureParallelLp, ProbeFeatureParallelZip, ProbeFeatureIsa, ProbeFeatureIsaIsdn, ProbeFeatureIsdn, ProbeFeatureKbd, ProbeFeatureProm, ProbeFeatureSbus, ProbeFeatureInt, ProbeFeatureBraille, ProbeFeatureBrailleAlva, ProbeFeatureBrailleFhp, ProbeFeatureBrailleHt, ProbeFeatureIgnx11, ProbeFeatureSys, ProbeFeatureBiosVbe, ProbeFeatureIsapnpOld, ProbeFeatureIsapnpNew, ProbeFeatureIsapnpMod, ProbeFeatureBrailleBaum, ProbeFeatureManual, ProbeFeatureFb, ProbeFeatureVeth, ProbeFeaturePppoe, ProbeFeatureScan, ProbeFeaturePcmcia, ProbeFeatureFork, ProbeFeatureParallelImm, ProbeFeatureS390, ProbeFeatureCpuemu, ProbeFeatureSysfs, ProbeFeatureS390disks, ProbeFeatureUdev, ProbeFeatureBlock, ProbeFeatureBlockCdrom, ProbeFeatureBlockPart, ProbeFeatureEdd, ProbeFeatureEddMod, ProbeFeatureBiosDdc, ProbeFeatureBiosFb, ProbeFeatureBiosMode, ProbeFeatureInput, ProbeFeatureBlockMods, ProbeFeatureBiosVesa, ProbeFeatureCpuemuDebug, ProbeFeatureScsiNoserial, ProbeFeatureWlan, ProbeFeatureBiosCrc, ProbeFeatureHal, ProbeFeatureBiosVram, ProbeFeatureBiosAcpi, ProbeFeatureBiosDdcPorts, ProbeFeatureModulesPata, ProbeFeatureNetEeprom, ProbeFeatureX86emu, ProbeFeatureMax, ProbeFeatureLxrc, ProbeFeatureDefault, ProbeFeatureAll}

var _ProbeFeatureNameToValueMap = map[string]ProbeFeature{
	_ProbeFeatureName[0:6]:          ProbeFeatureMemory,
	_ProbeFeatureLowerName[0:6]:     ProbeFeatureMemory,
	_ProbeFeatureName[6:9]:          ProbeFeaturePci,
	_ProbeFeatureLowerName[6:9]:     ProbeFeaturePci,
	_ProbeFeatureName[9:15]:         ProbeFeatureIsapnp,
	_ProbeFeatureLowerName[9:15]:    ProbeFeatureIsapnp,
	_ProbeFeatureName[15:18]:        ProbeFeatureNet,
	_ProbeFeatureLowerName[15:18]:   ProbeFeatureNet,
	_ProbeFeatureName[18:24]:        ProbeFeatureFloppy,
	_ProbeFeatureLowerName[18:24]:   ProbeFeatureFloppy,
	_ProbeFeatureName[24:28]:        ProbeFeatureMisc,
	_ProbeFeatureLowerName[24:28]:   ProbeFeatureMisc,
	_ProbeFeatureName[28:39]:        ProbeFeatureMiscSerial,
	_ProbeFeatureLowerName[28:39]:   ProbeFeatureMiscSerial,
	_ProbeFeatureName[39:47]:        ProbeFeatureMiscPar,
	_ProbeFeatureLowerName[39:47]:   ProbeFeatureMiscPar,
	_ProbeFeatureName[47:58]:        ProbeFeatureMiscFloppy,
	_ProbeFeatureLowerName[47:58]:   ProbeFeatureMiscFloppy,
	_ProbeFeatureName[58:64]:        ProbeFeatureSerial,
	_ProbeFeatureLowerName[58:64]:   ProbeFeatureSerial,
	_ProbeFeatureName[64:67]:        ProbeFeatureCpu,
	_ProbeFeatureLowerName[64:67]:   ProbeFeatureCpu,
	_ProbeFeatureName[67:71]:        ProbeFeatureBios,
	_ProbeFeatureLowerName[67:71]:   ProbeFeatureBios,
	_ProbeFeatureName[71:78]:        ProbeFeatureMonitor,
	_ProbeFeatureLowerName[71:78]:   ProbeFeatureMonitor,
	_ProbeFeatureName[78:83]:        ProbeFeatureMouse,
	_ProbeFeatureLowerName[78:83]:   ProbeFeatureMouse,
	_ProbeFeatureName[83:87]:        ProbeFeatureScsi,
	_ProbeFeatureLowerName[83:87]:   ProbeFeatureScsi,
	_ProbeFeatureName[87:90]:        ProbeFeatureUsb,
	_ProbeFeatureLowerName[87:90]:   ProbeFeatureUsb,
	_ProbeFeatureName[90:98]:        ProbeFeatureUsbMods,
	_ProbeFeatureLowerName[90:98]:   ProbeFeatureUsbMods,
	_ProbeFeatureName[98:101]:       ProbeFeatureAdb,
	_ProbeFeatureLowerName[98:101]:  ProbeFeatureAdb,
	_ProbeFeatureName[101:106]:      ProbeFeatureModem,
	_ProbeFeatureLowerName[101:106]: ProbeFeatureModem,
	_ProbeFeatureName[106:115]:      ProbeFeatureModemUsb,
	_ProbeFeatureLowerName[106:115]: ProbeFeatureModemUsb,
	_ProbeFeatureName[115:123]:      ProbeFeatureParallel,
	_ProbeFeatureLowerName[115:123]: ProbeFeatureParallel,
	_ProbeFeatureName[123:134]:      ProbeFeatureParallelLp,
	_ProbeFeatureLowerName[123:134]: ProbeFeatureParallelLp,
	_ProbeFeatureName[134:146]:      ProbeFeatureParallelZip,
	_ProbeFeatureLowerName[134:146]: ProbeFeatureParallelZip,
	_ProbeFeatureName[146:149]:      ProbeFeatureIsa,
	_ProbeFeatureLowerName[146:149]: ProbeFeatureIsa,
	_ProbeFeatureName[149:157]:      ProbeFeatureIsaIsdn,
	_ProbeFeatureLowerName[149:157]: ProbeFeatureIsaIsdn,
	_ProbeFeatureName[157:161]:      ProbeFeatureIsdn,
	_ProbeFeatureLowerName[157:161]: ProbeFeatureIsdn,
	_ProbeFeatureName[161:164]:      ProbeFeatureKbd,
	_ProbeFeatureLowerName[161:164]: ProbeFeatureKbd,
	_ProbeFeatureName[164:168]:      ProbeFeatureProm,
	_ProbeFeatureLowerName[164:168]: ProbeFeatureProm,
	_ProbeFeatureName[168:172]:      ProbeFeatureSbus,
	_ProbeFeatureLowerName[168:172]: ProbeFeatureSbus,
	_ProbeFeatureName[172:175]:      ProbeFeatureInt,
	_ProbeFeatureLowerName[172:175]: ProbeFeatureInt,
	_ProbeFeatureName[175:182]:      ProbeFeatureBraille,
	_ProbeFeatureLowerName[175:182]: ProbeFeatureBraille,
	_ProbeFeatureName[182:194]:      ProbeFeatureBrailleAlva,
	_ProbeFeatureLowerName[182:194]: ProbeFeatureBrailleAlva,
	_ProbeFeatureName[194:205]:      ProbeFeatureBrailleFhp,
	_ProbeFeatureLowerName[194:205]: ProbeFeatureBrailleFhp,
	_ProbeFeatureName[205:215]:      ProbeFeatureBrailleHt,
	_ProbeFeatureLowerName[205:215]: ProbeFeatureBrailleHt,
	_ProbeFeatureName[215:221]:      ProbeFeatureIgnx11,
	_ProbeFeatureLowerName[215:221]: ProbeFeatureIgnx11,
	_ProbeFeatureName[221:224]:      ProbeFeatureSys,
	_ProbeFeatureLowerName[221:224]: ProbeFeatureSys,
	_ProbeFeatureName[224:232]:      ProbeFeatureBiosVbe,
	_ProbeFeatureLowerName[224:232]: ProbeFeatureBiosVbe,
	_ProbeFeatureName[232:242]:      ProbeFeatureIsapnpOld,
	_ProbeFeatureLowerName[232:242]: ProbeFeatureIsapnpOld,
	_ProbeFeatureName[242:252]:      ProbeFeatureIsapnpNew,
	_ProbeFeatureLowerName[242:252]: ProbeFeatureIsapnpNew,
	_ProbeFeatureName[252:262]:      ProbeFeatureIsapnpMod,
	_ProbeFeatureLowerName[252:262]: ProbeFeatureIsapnpMod,
	_ProbeFeatureName[262:274]:      ProbeFeatureBrailleBaum,
	_ProbeFeatureLowerName[262:274]: ProbeFeatureBrailleBaum,
	_ProbeFeatureName[274:280]:      ProbeFeatureManual,
	_ProbeFeatureLowerName[274:280]: ProbeFeatureManual,
	_ProbeFeatureName[280:282]:      ProbeFeatureFb,
	_ProbeFeatureLowerName[280:282]: ProbeFeatureFb,
	_ProbeFeatureName[282:286]:      ProbeFeatureVeth,
	_ProbeFeatureLowerName[282:286]: ProbeFeatureVeth,
	_ProbeFeatureName[286:291]:      ProbeFeaturePppoe,
	_ProbeFeatureLowerName[286:291]: ProbeFeaturePppoe,
	_ProbeFeatureName[291:295]:      ProbeFeatureScan,
	_ProbeFeatureLowerName[291:295]: ProbeFeatureScan,
	_ProbeFeatureName[295:301]:      ProbeFeaturePcmcia,
	_ProbeFeatureLowerName[295:301]: ProbeFeaturePcmcia,
	_ProbeFeatureName[301:305]:      ProbeFeatureFork,
	_ProbeFeatureLowerName[301:305]: ProbeFeatureFork,
	_ProbeFeatureName[305:317]:      ProbeFeatureParallelImm,
	_ProbeFeatureLowerName[305:317]: ProbeFeatureParallelImm,
	_ProbeFeatureName[317:321]:      ProbeFeatureS390,
	_ProbeFeatureLowerName[317:321]: ProbeFeatureS390,
	_ProbeFeatureName[321:327]:      ProbeFeatureCpuemu,
	_ProbeFeatureLowerName[321:327]: ProbeFeatureCpuemu,
	_ProbeFeatureName[327:332]:      ProbeFeatureSysfs,
	_ProbeFeatureLowerName[327:332]: ProbeFeatureSysfs,
	_ProbeFeatureName[332:341]:      ProbeFeatureS390disks,
	_ProbeFeatureLowerName[332:341]: ProbeFeatureS390disks,
	_ProbeFeatureName[341:345]:      ProbeFeatureUdev,
	_ProbeFeatureLowerName[341:345]: ProbeFeatureUdev,
	_ProbeFeatureName[345:350]:      ProbeFeatureBlock,
	_ProbeFeatureLowerName[345:350]: ProbeFeatureBlock,
	_ProbeFeatureName[350:361]:      ProbeFeatureBlockCdrom,
	_ProbeFeatureLowerName[350:361]: ProbeFeatureBlockCdrom,
	_ProbeFeatureName[361:371]:      ProbeFeatureBlockPart,
	_ProbeFeatureLowerName[361:371]: ProbeFeatureBlockPart,
	_ProbeFeatureName[371:374]:      ProbeFeatureEdd,
	_ProbeFeatureLowerName[371:374]: ProbeFeatureEdd,
	_ProbeFeatureName[374:381]:      ProbeFeatureEddMod,
	_ProbeFeatureLowerName[374:381]: ProbeFeatureEddMod,
	_ProbeFeatureName[381:389]:      ProbeFeatureBiosDdc,
	_ProbeFeatureLowerName[381:389]: ProbeFeatureBiosDdc,
	_ProbeFeatureName[389:396]:      ProbeFeatureBiosFb,
	_ProbeFeatureLowerName[389:396]: ProbeFeatureBiosFb,
	_ProbeFeatureName[396:405]:      ProbeFeatureBiosMode,
	_ProbeFeatureLowerName[396:405]: ProbeFeatureBiosMode,
	_ProbeFeatureName[405:410]:      ProbeFeatureInput,
	_ProbeFeatureLowerName[405:410]: ProbeFeatureInput,
	_ProbeFeatureName[410:420]:      ProbeFeatureBlockMods,
	_ProbeFeatureLowerName[410:420]: ProbeFeatureBlockMods,
	_ProbeFeatureName[420:429]:      ProbeFeatureBiosVesa,
	_ProbeFeatureLowerName[420:429]: ProbeFeatureBiosVesa,
	_ProbeFeatureName[429:441]:      ProbeFeatureCpuemuDebug,
	_ProbeFeatureLowerName[429:441]: ProbeFeatureCpuemuDebug,
	_ProbeFeatureName[441:454]:      ProbeFeatureScsiNoserial,
	_ProbeFeatureLowerName[441:454]: ProbeFeatureScsiNoserial,
	_ProbeFeatureName[454:458]:      ProbeFeatureWlan,
	_ProbeFeatureLowerName[454:458]: ProbeFeatureWlan,
	_ProbeFeatureName[458:466]:      ProbeFeatureBiosCrc,
	_ProbeFeatureLowerName[458:466]: ProbeFeatureBiosCrc,
	_ProbeFeatureName[466:469]:      ProbeFeatureHal,
	_ProbeFeatureLowerName[466:469]: ProbeFeatureHal,
	_ProbeFeatureName[469:478]:      ProbeFeatureBiosVram,
	_ProbeFeatureLowerName[469:478]: ProbeFeatureBiosVram,
	_ProbeFeatureName[478:487]:      ProbeFeatureBiosAcpi,
	_ProbeFeatureLowerName[478:487]: ProbeFeatureBiosAcpi,
	_ProbeFeatureName[487:501]:      ProbeFeatureBiosDdcPorts,
	_ProbeFeatureLowerName[487:501]: ProbeFeatureBiosDdcPorts,
	_ProbeFeatureName[501:513]:      ProbeFeatureModulesPata,
	_ProbeFeatureLowerName[501:513]: ProbeFeatureModulesPata,
	_ProbeFeatureName[513:523]:      ProbeFeatureNetEeprom,
	_ProbeFeatureLowerName[513:523]: ProbeFeatureNetEeprom,
	_ProbeFeatureName[523:529]:      ProbeFeatureX86emu,
	_ProbeFeatureLowerName[523:529]: ProbeFeatureX86emu,
	_ProbeFeatureName[529:532]:      ProbeFeatureMax,
	_ProbeFeatureLowerName[529:532]: ProbeFeatureMax,
	_ProbeFeatureName[532:536]:      ProbeFeatureLxrc,
	_ProbeFeatureLowerName[532:536]: ProbeFeatureLxrc,
	_ProbeFeatureName[536:543]:      ProbeFeatureDefault,
	_ProbeFeatureLowerName[536:543]: ProbeFeatureDefault,
	_ProbeFeatureName[543:546]:      ProbeFeatureAll,
	_ProbeFeatureLowerName[543:546]: ProbeFeatureAll,
}

var _ProbeFeatureNames = []string{
	_ProbeFeatureName[0:6],
	_ProbeFeatureName[6:9],
	_ProbeFeatureName[9:15],
	_ProbeFeatureName[15:18],
	_ProbeFeatureName[18:24],
	_ProbeFeatureName[24:28],
	_ProbeFeatureName[28:39],
	_ProbeFeatureName[39:47],
	_ProbeFeatureName[47:58],
	_ProbeFeatureName[58:64],
	_ProbeFeatureName[64:67],
	_ProbeFeatureName[67:71],
	_ProbeFeatureName[71:78],
	_ProbeFeatureName[78:83],
	_ProbeFeatureName[83:87],
	_ProbeFeatureName[87:90],
	_ProbeFeatureName[90:98],
	_ProbeFeatureName[98:101],
	_ProbeFeatureName[101:106],
	_ProbeFeatureName[106:115],
	_ProbeFeatureName[115:123],
	_ProbeFeatureName[123:134],
	_ProbeFeatureName[134:146],
	_ProbeFeatureName[146:149],
	_ProbeFeatureName[149:157],
	_ProbeFeatureName[157:161],
	_ProbeFeatureName[161:164],
	_ProbeFeatureName[164:168],
	_ProbeFeatureName[168:172],
	_ProbeFeatureName[172:175],
	_ProbeFeatureName[175:182],
	_ProbeFeatureName[182:194],
	_ProbeFeatureName[194:205],
	_ProbeFeatureName[205:215],
	_ProbeFeatureName[215:221],
	_ProbeFeatureName[221:224],
	_ProbeFeatureName[224:232],
	_ProbeFeatureName[232:242],
	_ProbeFeatureName[242:252],
	_ProbeFeatureName[252:262],
	_ProbeFeatureName[262:274],
	_ProbeFeatureName[274:280],
	_ProbeFeatureName[280:282],
	_ProbeFeatureName[282:286],
	_ProbeFeatureName[286:291],
	_ProbeFeatureName[291:295],
	_ProbeFeatureName[295:301],
	_ProbeFeatureName[301:305],
	_ProbeFeatureName[305:317],
	_ProbeFeatureName[317:321],
	_ProbeFeatureName[321:327],
	_ProbeFeatureName[327:332],
	_ProbeFeatureName[332:341],
	_ProbeFeatureName[341:345],
	_ProbeFeatureName[345:350],
	_ProbeFeatureName[350:361],
	_ProbeFeatureName[361:371],
	_ProbeFeatureName[371:374],
	_ProbeFeatureName[374:381],
	_ProbeFeatureName[381:389],
	_ProbeFeatureName[389:396],
	_ProbeFeatureName[396:405],
	_ProbeFeatureName[405:410],
	_ProbeFeatureName[410:420],
	_ProbeFeatureName[420:429],
	_ProbeFeatureName[429:441],
	_ProbeFeatureName[441:454],
	_ProbeFeatureName[454:458],
	_ProbeFeatureName[458:466],
	_ProbeFeatureName[466:469],
	_ProbeFeatureName[469:478],
	_ProbeFeatureName[478:487],
	_ProbeFeatureName[487:501],
	_ProbeFeatureName[501:513],
	_ProbeFeatureName[513:523],
	_ProbeFeatureName[523:529],
	_ProbeFeatureName[529:532],
	_ProbeFeatureName[532:536],
	_ProbeFeatureName[536:543],
	_ProbeFeatureName[543:546],
}

// ProbeFeatureString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ProbeFeatureString(s string) (ProbeFeature, error) {
	if val, ok := _ProbeFeatureNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ProbeFeatureNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ProbeFeature values", s)
}

// ProbeFeatureValues returns all values of the enum
func ProbeFeatureValues() []ProbeFeature {
	return _ProbeFeatureValues
}

// ProbeFeatureStrings returns a slice of all String values of the enum
func ProbeFeatureStrings() []string {
	strs := make([]string, len(_ProbeFeatureNames))
	copy(strs, _ProbeFeatureNames)
	return strs
}

// IsAProbeFeature returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ProbeFeature) IsAProbeFeature() bool {
	for _, v := range _ProbeFeatureValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ProbeFeature
func (i ProbeFeature) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ProbeFeature
func (i *ProbeFeature) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ProbeFeature should be a string, got %s", data)
	}

	var err error
	*i, err = ProbeFeatureString(s)
	return err
}
