// Code generated by "enumer -type=HardwareItem -json -transform=snake -trimprefix HardwareItem -output=./report_enum_hardware_item.go"; DO NOT EDIT.

package hwinfo

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _HardwareItemName = "nonesyscpukeyboardbraillemousejoystickprinterscannerchipcardmonitortvdisplayframebuffercamerasoundstorage_ctrlnetwork_ctrlisdnmodemnetworkdiskpartitioncdromfloppymanualusb_ctrlusbbiospciisapnpbridgehubscsiidememorydvbpcmciapcmcia_ctrlieee1394ieee1394_ctrlhotplughotplug_ctrlzippppoewlanredasddslblocktapevbebluetoothfingerprintmmc_ctrlnvmeunknownall"

var _HardwareItemIndex = [...]uint16{0, 4, 7, 10, 18, 25, 30, 38, 45, 52, 60, 67, 69, 76, 87, 93, 98, 110, 122, 126, 131, 138, 142, 151, 156, 162, 168, 176, 179, 183, 186, 192, 198, 201, 205, 208, 214, 217, 223, 234, 242, 255, 262, 274, 277, 282, 286, 292, 295, 300, 304, 307, 316, 327, 335, 339, 346, 349}

const _HardwareItemLowerName = "nonesyscpukeyboardbraillemousejoystickprinterscannerchipcardmonitortvdisplayframebuffercamerasoundstorage_ctrlnetwork_ctrlisdnmodemnetworkdiskpartitioncdromfloppymanualusb_ctrlusbbiospciisapnpbridgehubscsiidememorydvbpcmciapcmcia_ctrlieee1394ieee1394_ctrlhotplughotplug_ctrlzippppoewlanredasddslblocktapevbebluetoothfingerprintmmc_ctrlnvmeunknownall"

func (i HardwareItem) String() string {
	if i >= HardwareItem(len(_HardwareItemIndex)-1) {
		return fmt.Sprintf("HardwareItem(%d)", i)
	}
	return _HardwareItemName[_HardwareItemIndex[i]:_HardwareItemIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _HardwareItemNoOp() {
	var x [1]struct{}
	_ = x[HardwareItemNone-(0)]
	_ = x[HardwareItemSys-(1)]
	_ = x[HardwareItemCpu-(2)]
	_ = x[HardwareItemKeyboard-(3)]
	_ = x[HardwareItemBraille-(4)]
	_ = x[HardwareItemMouse-(5)]
	_ = x[HardwareItemJoystick-(6)]
	_ = x[HardwareItemPrinter-(7)]
	_ = x[HardwareItemScanner-(8)]
	_ = x[HardwareItemChipcard-(9)]
	_ = x[HardwareItemMonitor-(10)]
	_ = x[HardwareItemTv-(11)]
	_ = x[HardwareItemDisplay-(12)]
	_ = x[HardwareItemFramebuffer-(13)]
	_ = x[HardwareItemCamera-(14)]
	_ = x[HardwareItemSound-(15)]
	_ = x[HardwareItemStorageCtrl-(16)]
	_ = x[HardwareItemNetworkCtrl-(17)]
	_ = x[HardwareItemIsdn-(18)]
	_ = x[HardwareItemModem-(19)]
	_ = x[HardwareItemNetwork-(20)]
	_ = x[HardwareItemDisk-(21)]
	_ = x[HardwareItemPartition-(22)]
	_ = x[HardwareItemCdrom-(23)]
	_ = x[HardwareItemFloppy-(24)]
	_ = x[HardwareItemManual-(25)]
	_ = x[HardwareItemUsbCtrl-(26)]
	_ = x[HardwareItemUsb-(27)]
	_ = x[HardwareItemBios-(28)]
	_ = x[HardwareItemPci-(29)]
	_ = x[HardwareItemIsapnp-(30)]
	_ = x[HardwareItemBridge-(31)]
	_ = x[HardwareItemHub-(32)]
	_ = x[HardwareItemScsi-(33)]
	_ = x[HardwareItemIde-(34)]
	_ = x[HardwareItemMemory-(35)]
	_ = x[HardwareItemDvb-(36)]
	_ = x[HardwareItemPcmcia-(37)]
	_ = x[HardwareItemPcmciaCtrl-(38)]
	_ = x[HardwareItemIeee1394-(39)]
	_ = x[HardwareItemIeee1394Ctrl-(40)]
	_ = x[HardwareItemHotplug-(41)]
	_ = x[HardwareItemHotplugCtrl-(42)]
	_ = x[HardwareItemZip-(43)]
	_ = x[HardwareItemPppoe-(44)]
	_ = x[HardwareItemWlan-(45)]
	_ = x[HardwareItemRedasd-(46)]
	_ = x[HardwareItemDsl-(47)]
	_ = x[HardwareItemBlock-(48)]
	_ = x[HardwareItemTape-(49)]
	_ = x[HardwareItemVbe-(50)]
	_ = x[HardwareItemBluetooth-(51)]
	_ = x[HardwareItemFingerprint-(52)]
	_ = x[HardwareItemMmcCtrl-(53)]
	_ = x[HardwareItemNvme-(54)]
	_ = x[HardwareItemUnknown-(55)]
	_ = x[HardwareItemAll-(56)]
}

var _HardwareItemValues = []HardwareItem{HardwareItemNone, HardwareItemSys, HardwareItemCpu, HardwareItemKeyboard, HardwareItemBraille, HardwareItemMouse, HardwareItemJoystick, HardwareItemPrinter, HardwareItemScanner, HardwareItemChipcard, HardwareItemMonitor, HardwareItemTv, HardwareItemDisplay, HardwareItemFramebuffer, HardwareItemCamera, HardwareItemSound, HardwareItemStorageCtrl, HardwareItemNetworkCtrl, HardwareItemIsdn, HardwareItemModem, HardwareItemNetwork, HardwareItemDisk, HardwareItemPartition, HardwareItemCdrom, HardwareItemFloppy, HardwareItemManual, HardwareItemUsbCtrl, HardwareItemUsb, HardwareItemBios, HardwareItemPci, HardwareItemIsapnp, HardwareItemBridge, HardwareItemHub, HardwareItemScsi, HardwareItemIde, HardwareItemMemory, HardwareItemDvb, HardwareItemPcmcia, HardwareItemPcmciaCtrl, HardwareItemIeee1394, HardwareItemIeee1394Ctrl, HardwareItemHotplug, HardwareItemHotplugCtrl, HardwareItemZip, HardwareItemPppoe, HardwareItemWlan, HardwareItemRedasd, HardwareItemDsl, HardwareItemBlock, HardwareItemTape, HardwareItemVbe, HardwareItemBluetooth, HardwareItemFingerprint, HardwareItemMmcCtrl, HardwareItemNvme, HardwareItemUnknown, HardwareItemAll}

var _HardwareItemNameToValueMap = map[string]HardwareItem{
	_HardwareItemName[0:4]:          HardwareItemNone,
	_HardwareItemLowerName[0:4]:     HardwareItemNone,
	_HardwareItemName[4:7]:          HardwareItemSys,
	_HardwareItemLowerName[4:7]:     HardwareItemSys,
	_HardwareItemName[7:10]:         HardwareItemCpu,
	_HardwareItemLowerName[7:10]:    HardwareItemCpu,
	_HardwareItemName[10:18]:        HardwareItemKeyboard,
	_HardwareItemLowerName[10:18]:   HardwareItemKeyboard,
	_HardwareItemName[18:25]:        HardwareItemBraille,
	_HardwareItemLowerName[18:25]:   HardwareItemBraille,
	_HardwareItemName[25:30]:        HardwareItemMouse,
	_HardwareItemLowerName[25:30]:   HardwareItemMouse,
	_HardwareItemName[30:38]:        HardwareItemJoystick,
	_HardwareItemLowerName[30:38]:   HardwareItemJoystick,
	_HardwareItemName[38:45]:        HardwareItemPrinter,
	_HardwareItemLowerName[38:45]:   HardwareItemPrinter,
	_HardwareItemName[45:52]:        HardwareItemScanner,
	_HardwareItemLowerName[45:52]:   HardwareItemScanner,
	_HardwareItemName[52:60]:        HardwareItemChipcard,
	_HardwareItemLowerName[52:60]:   HardwareItemChipcard,
	_HardwareItemName[60:67]:        HardwareItemMonitor,
	_HardwareItemLowerName[60:67]:   HardwareItemMonitor,
	_HardwareItemName[67:69]:        HardwareItemTv,
	_HardwareItemLowerName[67:69]:   HardwareItemTv,
	_HardwareItemName[69:76]:        HardwareItemDisplay,
	_HardwareItemLowerName[69:76]:   HardwareItemDisplay,
	_HardwareItemName[76:87]:        HardwareItemFramebuffer,
	_HardwareItemLowerName[76:87]:   HardwareItemFramebuffer,
	_HardwareItemName[87:93]:        HardwareItemCamera,
	_HardwareItemLowerName[87:93]:   HardwareItemCamera,
	_HardwareItemName[93:98]:        HardwareItemSound,
	_HardwareItemLowerName[93:98]:   HardwareItemSound,
	_HardwareItemName[98:110]:       HardwareItemStorageCtrl,
	_HardwareItemLowerName[98:110]:  HardwareItemStorageCtrl,
	_HardwareItemName[110:122]:      HardwareItemNetworkCtrl,
	_HardwareItemLowerName[110:122]: HardwareItemNetworkCtrl,
	_HardwareItemName[122:126]:      HardwareItemIsdn,
	_HardwareItemLowerName[122:126]: HardwareItemIsdn,
	_HardwareItemName[126:131]:      HardwareItemModem,
	_HardwareItemLowerName[126:131]: HardwareItemModem,
	_HardwareItemName[131:138]:      HardwareItemNetwork,
	_HardwareItemLowerName[131:138]: HardwareItemNetwork,
	_HardwareItemName[138:142]:      HardwareItemDisk,
	_HardwareItemLowerName[138:142]: HardwareItemDisk,
	_HardwareItemName[142:151]:      HardwareItemPartition,
	_HardwareItemLowerName[142:151]: HardwareItemPartition,
	_HardwareItemName[151:156]:      HardwareItemCdrom,
	_HardwareItemLowerName[151:156]: HardwareItemCdrom,
	_HardwareItemName[156:162]:      HardwareItemFloppy,
	_HardwareItemLowerName[156:162]: HardwareItemFloppy,
	_HardwareItemName[162:168]:      HardwareItemManual,
	_HardwareItemLowerName[162:168]: HardwareItemManual,
	_HardwareItemName[168:176]:      HardwareItemUsbCtrl,
	_HardwareItemLowerName[168:176]: HardwareItemUsbCtrl,
	_HardwareItemName[176:179]:      HardwareItemUsb,
	_HardwareItemLowerName[176:179]: HardwareItemUsb,
	_HardwareItemName[179:183]:      HardwareItemBios,
	_HardwareItemLowerName[179:183]: HardwareItemBios,
	_HardwareItemName[183:186]:      HardwareItemPci,
	_HardwareItemLowerName[183:186]: HardwareItemPci,
	_HardwareItemName[186:192]:      HardwareItemIsapnp,
	_HardwareItemLowerName[186:192]: HardwareItemIsapnp,
	_HardwareItemName[192:198]:      HardwareItemBridge,
	_HardwareItemLowerName[192:198]: HardwareItemBridge,
	_HardwareItemName[198:201]:      HardwareItemHub,
	_HardwareItemLowerName[198:201]: HardwareItemHub,
	_HardwareItemName[201:205]:      HardwareItemScsi,
	_HardwareItemLowerName[201:205]: HardwareItemScsi,
	_HardwareItemName[205:208]:      HardwareItemIde,
	_HardwareItemLowerName[205:208]: HardwareItemIde,
	_HardwareItemName[208:214]:      HardwareItemMemory,
	_HardwareItemLowerName[208:214]: HardwareItemMemory,
	_HardwareItemName[214:217]:      HardwareItemDvb,
	_HardwareItemLowerName[214:217]: HardwareItemDvb,
	_HardwareItemName[217:223]:      HardwareItemPcmcia,
	_HardwareItemLowerName[217:223]: HardwareItemPcmcia,
	_HardwareItemName[223:234]:      HardwareItemPcmciaCtrl,
	_HardwareItemLowerName[223:234]: HardwareItemPcmciaCtrl,
	_HardwareItemName[234:242]:      HardwareItemIeee1394,
	_HardwareItemLowerName[234:242]: HardwareItemIeee1394,
	_HardwareItemName[242:255]:      HardwareItemIeee1394Ctrl,
	_HardwareItemLowerName[242:255]: HardwareItemIeee1394Ctrl,
	_HardwareItemName[255:262]:      HardwareItemHotplug,
	_HardwareItemLowerName[255:262]: HardwareItemHotplug,
	_HardwareItemName[262:274]:      HardwareItemHotplugCtrl,
	_HardwareItemLowerName[262:274]: HardwareItemHotplugCtrl,
	_HardwareItemName[274:277]:      HardwareItemZip,
	_HardwareItemLowerName[274:277]: HardwareItemZip,
	_HardwareItemName[277:282]:      HardwareItemPppoe,
	_HardwareItemLowerName[277:282]: HardwareItemPppoe,
	_HardwareItemName[282:286]:      HardwareItemWlan,
	_HardwareItemLowerName[282:286]: HardwareItemWlan,
	_HardwareItemName[286:292]:      HardwareItemRedasd,
	_HardwareItemLowerName[286:292]: HardwareItemRedasd,
	_HardwareItemName[292:295]:      HardwareItemDsl,
	_HardwareItemLowerName[292:295]: HardwareItemDsl,
	_HardwareItemName[295:300]:      HardwareItemBlock,
	_HardwareItemLowerName[295:300]: HardwareItemBlock,
	_HardwareItemName[300:304]:      HardwareItemTape,
	_HardwareItemLowerName[300:304]: HardwareItemTape,
	_HardwareItemName[304:307]:      HardwareItemVbe,
	_HardwareItemLowerName[304:307]: HardwareItemVbe,
	_HardwareItemName[307:316]:      HardwareItemBluetooth,
	_HardwareItemLowerName[307:316]: HardwareItemBluetooth,
	_HardwareItemName[316:327]:      HardwareItemFingerprint,
	_HardwareItemLowerName[316:327]: HardwareItemFingerprint,
	_HardwareItemName[327:335]:      HardwareItemMmcCtrl,
	_HardwareItemLowerName[327:335]: HardwareItemMmcCtrl,
	_HardwareItemName[335:339]:      HardwareItemNvme,
	_HardwareItemLowerName[335:339]: HardwareItemNvme,
	_HardwareItemName[339:346]:      HardwareItemUnknown,
	_HardwareItemLowerName[339:346]: HardwareItemUnknown,
	_HardwareItemName[346:349]:      HardwareItemAll,
	_HardwareItemLowerName[346:349]: HardwareItemAll,
}

var _HardwareItemNames = []string{
	_HardwareItemName[0:4],
	_HardwareItemName[4:7],
	_HardwareItemName[7:10],
	_HardwareItemName[10:18],
	_HardwareItemName[18:25],
	_HardwareItemName[25:30],
	_HardwareItemName[30:38],
	_HardwareItemName[38:45],
	_HardwareItemName[45:52],
	_HardwareItemName[52:60],
	_HardwareItemName[60:67],
	_HardwareItemName[67:69],
	_HardwareItemName[69:76],
	_HardwareItemName[76:87],
	_HardwareItemName[87:93],
	_HardwareItemName[93:98],
	_HardwareItemName[98:110],
	_HardwareItemName[110:122],
	_HardwareItemName[122:126],
	_HardwareItemName[126:131],
	_HardwareItemName[131:138],
	_HardwareItemName[138:142],
	_HardwareItemName[142:151],
	_HardwareItemName[151:156],
	_HardwareItemName[156:162],
	_HardwareItemName[162:168],
	_HardwareItemName[168:176],
	_HardwareItemName[176:179],
	_HardwareItemName[179:183],
	_HardwareItemName[183:186],
	_HardwareItemName[186:192],
	_HardwareItemName[192:198],
	_HardwareItemName[198:201],
	_HardwareItemName[201:205],
	_HardwareItemName[205:208],
	_HardwareItemName[208:214],
	_HardwareItemName[214:217],
	_HardwareItemName[217:223],
	_HardwareItemName[223:234],
	_HardwareItemName[234:242],
	_HardwareItemName[242:255],
	_HardwareItemName[255:262],
	_HardwareItemName[262:274],
	_HardwareItemName[274:277],
	_HardwareItemName[277:282],
	_HardwareItemName[282:286],
	_HardwareItemName[286:292],
	_HardwareItemName[292:295],
	_HardwareItemName[295:300],
	_HardwareItemName[300:304],
	_HardwareItemName[304:307],
	_HardwareItemName[307:316],
	_HardwareItemName[316:327],
	_HardwareItemName[327:335],
	_HardwareItemName[335:339],
	_HardwareItemName[339:346],
	_HardwareItemName[346:349],
}

// HardwareItemString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func HardwareItemString(s string) (HardwareItem, error) {
	if val, ok := _HardwareItemNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _HardwareItemNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to HardwareItem values", s)
}

// HardwareItemValues returns all values of the enum
func HardwareItemValues() []HardwareItem {
	return _HardwareItemValues
}

// HardwareItemStrings returns a slice of all String values of the enum
func HardwareItemStrings() []string {
	strs := make([]string, len(_HardwareItemNames))
	copy(strs, _HardwareItemNames)
	return strs
}

// IsAHardwareItem returns "true" if the value is listed in the enum definition. "false" otherwise
func (i HardwareItem) IsAHardwareItem() bool {
	for _, v := range _HardwareItemValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for HardwareItem
func (i HardwareItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for HardwareItem
func (i *HardwareItem) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("HardwareItem should be a string, got %s", data)
	}

	var err error
	*i, err = HardwareItemString(s)
	return err
}
