// Code generated by "enumer -type=ResourceType -json -trimprefix ResourceType"; DO NOT EDIT.

package hwinfo

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _ResourceTypeName = "ResourceAnyResourcePhysMemResourceMemResourceIoResourceIrqResourceDmaResourceMonitorResourceSizeResourceDisk_geoResourceCacheResourceBaudResourceInitStringsResourcePppdOptionResourceFramebufferResourceHwaddrResourceLinkResourceWlanResourceFcResourcePhwaddr"

var _ResourceTypeIndex = [...]uint16{0, 11, 26, 37, 47, 58, 69, 84, 96, 112, 125, 137, 156, 174, 193, 207, 219, 231, 241, 256}

const _ResourceTypeLowerName = "resourceanyresourcephysmemresourcememresourceioresourceirqresourcedmaresourcemonitorresourcesizeresourcedisk_georesourcecacheresourcebaudresourceinitstringsresourcepppdoptionresourceframebufferresourcehwaddrresourcelinkresourcewlanresourcefcresourcephwaddr"

func (i ResourceType) String() string {
	if i < 0 || i >= ResourceType(len(_ResourceTypeIndex)-1) {
		return fmt.Sprintf("ResourceType(%d)", i)
	}
	return _ResourceTypeName[_ResourceTypeIndex[i]:_ResourceTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ResourceTypeNoOp() {
	var x [1]struct{}
	_ = x[ResourceAny-(0)]
	_ = x[ResourcePhysMem-(1)]
	_ = x[ResourceMem-(2)]
	_ = x[ResourceIo-(3)]
	_ = x[ResourceIrq-(4)]
	_ = x[ResourceDma-(5)]
	_ = x[ResourceMonitor-(6)]
	_ = x[ResourceSize-(7)]
	_ = x[ResourceDisk_geo-(8)]
	_ = x[ResourceCache-(9)]
	_ = x[ResourceBaud-(10)]
	_ = x[ResourceInitStrings-(11)]
	_ = x[ResourcePppdOption-(12)]
	_ = x[ResourceFramebuffer-(13)]
	_ = x[ResourceHwaddr-(14)]
	_ = x[ResourceLink-(15)]
	_ = x[ResourceWlan-(16)]
	_ = x[ResourceFc-(17)]
	_ = x[ResourcePhwaddr-(18)]
}

var _ResourceTypeValues = []ResourceType{ResourceAny, ResourcePhysMem, ResourceMem, ResourceIo, ResourceIrq, ResourceDma, ResourceMonitor, ResourceSize, ResourceDisk_geo, ResourceCache, ResourceBaud, ResourceInitStrings, ResourcePppdOption, ResourceFramebuffer, ResourceHwaddr, ResourceLink, ResourceWlan, ResourceFc, ResourcePhwaddr}

var _ResourceTypeNameToValueMap = map[string]ResourceType{
	_ResourceTypeName[0:11]:         ResourceAny,
	_ResourceTypeLowerName[0:11]:    ResourceAny,
	_ResourceTypeName[11:26]:        ResourcePhysMem,
	_ResourceTypeLowerName[11:26]:   ResourcePhysMem,
	_ResourceTypeName[26:37]:        ResourceMem,
	_ResourceTypeLowerName[26:37]:   ResourceMem,
	_ResourceTypeName[37:47]:        ResourceIo,
	_ResourceTypeLowerName[37:47]:   ResourceIo,
	_ResourceTypeName[47:58]:        ResourceIrq,
	_ResourceTypeLowerName[47:58]:   ResourceIrq,
	_ResourceTypeName[58:69]:        ResourceDma,
	_ResourceTypeLowerName[58:69]:   ResourceDma,
	_ResourceTypeName[69:84]:        ResourceMonitor,
	_ResourceTypeLowerName[69:84]:   ResourceMonitor,
	_ResourceTypeName[84:96]:        ResourceSize,
	_ResourceTypeLowerName[84:96]:   ResourceSize,
	_ResourceTypeName[96:112]:       ResourceDisk_geo,
	_ResourceTypeLowerName[96:112]:  ResourceDisk_geo,
	_ResourceTypeName[112:125]:      ResourceCache,
	_ResourceTypeLowerName[112:125]: ResourceCache,
	_ResourceTypeName[125:137]:      ResourceBaud,
	_ResourceTypeLowerName[125:137]: ResourceBaud,
	_ResourceTypeName[137:156]:      ResourceInitStrings,
	_ResourceTypeLowerName[137:156]: ResourceInitStrings,
	_ResourceTypeName[156:174]:      ResourcePppdOption,
	_ResourceTypeLowerName[156:174]: ResourcePppdOption,
	_ResourceTypeName[174:193]:      ResourceFramebuffer,
	_ResourceTypeLowerName[174:193]: ResourceFramebuffer,
	_ResourceTypeName[193:207]:      ResourceHwaddr,
	_ResourceTypeLowerName[193:207]: ResourceHwaddr,
	_ResourceTypeName[207:219]:      ResourceLink,
	_ResourceTypeLowerName[207:219]: ResourceLink,
	_ResourceTypeName[219:231]:      ResourceWlan,
	_ResourceTypeLowerName[219:231]: ResourceWlan,
	_ResourceTypeName[231:241]:      ResourceFc,
	_ResourceTypeLowerName[231:241]: ResourceFc,
	_ResourceTypeName[241:256]:      ResourcePhwaddr,
	_ResourceTypeLowerName[241:256]: ResourcePhwaddr,
}

var _ResourceTypeNames = []string{
	_ResourceTypeName[0:11],
	_ResourceTypeName[11:26],
	_ResourceTypeName[26:37],
	_ResourceTypeName[37:47],
	_ResourceTypeName[47:58],
	_ResourceTypeName[58:69],
	_ResourceTypeName[69:84],
	_ResourceTypeName[84:96],
	_ResourceTypeName[96:112],
	_ResourceTypeName[112:125],
	_ResourceTypeName[125:137],
	_ResourceTypeName[137:156],
	_ResourceTypeName[156:174],
	_ResourceTypeName[174:193],
	_ResourceTypeName[193:207],
	_ResourceTypeName[207:219],
	_ResourceTypeName[219:231],
	_ResourceTypeName[231:241],
	_ResourceTypeName[241:256],
}

// ResourceTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ResourceTypeString(s string) (ResourceType, error) {
	if val, ok := _ResourceTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ResourceTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ResourceType values", s)
}

// ResourceTypeValues returns all values of the enum
func ResourceTypeValues() []ResourceType {
	return _ResourceTypeValues
}

// ResourceTypeStrings returns a slice of all String values of the enum
func ResourceTypeStrings() []string {
	strs := make([]string, len(_ResourceTypeNames))
	copy(strs, _ResourceTypeNames)
	return strs
}

// IsAResourceType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ResourceType) IsAResourceType() bool {
	for _, v := range _ResourceTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ResourceType
func (i ResourceType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ResourceType
func (i *ResourceType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ResourceType should be a string, got %s", data)
	}

	var err error
	*i, err = ResourceTypeString(s)
	return err
}
