// Code generated by "enumer -type=ResourceType -json -trimprefix ResourceType"; DO NOT EDIT.

package hwinfo

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _ResourceTypeName = "AnyPhysMemMemIoIrqDmaMonitorSizeDiskGeoCacheBaudInitStringsPppdOptionFramebufferHwaddrLinkWlanFcPhwaddr"

var _ResourceTypeIndex = [...]uint8{0, 3, 10, 13, 15, 18, 21, 28, 32, 39, 44, 48, 59, 69, 80, 86, 90, 94, 96, 103}

const _ResourceTypeLowerName = "anyphysmemmemioirqdmamonitorsizediskgeocachebaudinitstringspppdoptionframebufferhwaddrlinkwlanfcphwaddr"

func (i ResourceType) String() string {
	if i < 0 || i >= ResourceType(len(_ResourceTypeIndex)-1) {
		return fmt.Sprintf("ResourceType(%d)", i)
	}
	return _ResourceTypeName[_ResourceTypeIndex[i]:_ResourceTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ResourceTypeNoOp() {
	var x [1]struct{}
	_ = x[ResourceTypeAny-(0)]
	_ = x[ResourceTypePhysMem-(1)]
	_ = x[ResourceTypeMem-(2)]
	_ = x[ResourceTypeIo-(3)]
	_ = x[ResourceTypeIrq-(4)]
	_ = x[ResourceTypeDma-(5)]
	_ = x[ResourceTypeMonitor-(6)]
	_ = x[ResourceTypeSize-(7)]
	_ = x[ResourceTypeDiskGeo-(8)]
	_ = x[ResourceTypeCache-(9)]
	_ = x[ResourceTypeBaud-(10)]
	_ = x[ResourceTypeInitStrings-(11)]
	_ = x[ResourceTypePppdOption-(12)]
	_ = x[ResourceTypeFramebuffer-(13)]
	_ = x[ResourceTypeHwaddr-(14)]
	_ = x[ResourceTypeLink-(15)]
	_ = x[ResourceTypeWlan-(16)]
	_ = x[ResourceTypeFc-(17)]
	_ = x[ResourceTypePhwaddr-(18)]
}

var _ResourceTypeValues = []ResourceType{ResourceTypeAny, ResourceTypePhysMem, ResourceTypeMem, ResourceTypeIo, ResourceTypeIrq, ResourceTypeDma, ResourceTypeMonitor, ResourceTypeSize, ResourceTypeDiskGeo, ResourceTypeCache, ResourceTypeBaud, ResourceTypeInitStrings, ResourceTypePppdOption, ResourceTypeFramebuffer, ResourceTypeHwaddr, ResourceTypeLink, ResourceTypeWlan, ResourceTypeFc, ResourceTypePhwaddr}

var _ResourceTypeNameToValueMap = map[string]ResourceType{
	_ResourceTypeName[0:3]:         ResourceTypeAny,
	_ResourceTypeLowerName[0:3]:    ResourceTypeAny,
	_ResourceTypeName[3:10]:        ResourceTypePhysMem,
	_ResourceTypeLowerName[3:10]:   ResourceTypePhysMem,
	_ResourceTypeName[10:13]:       ResourceTypeMem,
	_ResourceTypeLowerName[10:13]:  ResourceTypeMem,
	_ResourceTypeName[13:15]:       ResourceTypeIo,
	_ResourceTypeLowerName[13:15]:  ResourceTypeIo,
	_ResourceTypeName[15:18]:       ResourceTypeIrq,
	_ResourceTypeLowerName[15:18]:  ResourceTypeIrq,
	_ResourceTypeName[18:21]:       ResourceTypeDma,
	_ResourceTypeLowerName[18:21]:  ResourceTypeDma,
	_ResourceTypeName[21:28]:       ResourceTypeMonitor,
	_ResourceTypeLowerName[21:28]:  ResourceTypeMonitor,
	_ResourceTypeName[28:32]:       ResourceTypeSize,
	_ResourceTypeLowerName[28:32]:  ResourceTypeSize,
	_ResourceTypeName[32:39]:       ResourceTypeDiskGeo,
	_ResourceTypeLowerName[32:39]:  ResourceTypeDiskGeo,
	_ResourceTypeName[39:44]:       ResourceTypeCache,
	_ResourceTypeLowerName[39:44]:  ResourceTypeCache,
	_ResourceTypeName[44:48]:       ResourceTypeBaud,
	_ResourceTypeLowerName[44:48]:  ResourceTypeBaud,
	_ResourceTypeName[48:59]:       ResourceTypeInitStrings,
	_ResourceTypeLowerName[48:59]:  ResourceTypeInitStrings,
	_ResourceTypeName[59:69]:       ResourceTypePppdOption,
	_ResourceTypeLowerName[59:69]:  ResourceTypePppdOption,
	_ResourceTypeName[69:80]:       ResourceTypeFramebuffer,
	_ResourceTypeLowerName[69:80]:  ResourceTypeFramebuffer,
	_ResourceTypeName[80:86]:       ResourceTypeHwaddr,
	_ResourceTypeLowerName[80:86]:  ResourceTypeHwaddr,
	_ResourceTypeName[86:90]:       ResourceTypeLink,
	_ResourceTypeLowerName[86:90]:  ResourceTypeLink,
	_ResourceTypeName[90:94]:       ResourceTypeWlan,
	_ResourceTypeLowerName[90:94]:  ResourceTypeWlan,
	_ResourceTypeName[94:96]:       ResourceTypeFc,
	_ResourceTypeLowerName[94:96]:  ResourceTypeFc,
	_ResourceTypeName[96:103]:      ResourceTypePhwaddr,
	_ResourceTypeLowerName[96:103]: ResourceTypePhwaddr,
}

var _ResourceTypeNames = []string{
	_ResourceTypeName[0:3],
	_ResourceTypeName[3:10],
	_ResourceTypeName[10:13],
	_ResourceTypeName[13:15],
	_ResourceTypeName[15:18],
	_ResourceTypeName[18:21],
	_ResourceTypeName[21:28],
	_ResourceTypeName[28:32],
	_ResourceTypeName[32:39],
	_ResourceTypeName[39:44],
	_ResourceTypeName[44:48],
	_ResourceTypeName[48:59],
	_ResourceTypeName[59:69],
	_ResourceTypeName[69:80],
	_ResourceTypeName[80:86],
	_ResourceTypeName[86:90],
	_ResourceTypeName[90:94],
	_ResourceTypeName[94:96],
	_ResourceTypeName[96:103],
}

// ResourceTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ResourceTypeString(s string) (ResourceType, error) {
	if val, ok := _ResourceTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ResourceTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ResourceType values", s)
}

// ResourceTypeValues returns all values of the enum
func ResourceTypeValues() []ResourceType {
	return _ResourceTypeValues
}

// ResourceTypeStrings returns a slice of all String values of the enum
func ResourceTypeStrings() []string {
	strs := make([]string, len(_ResourceTypeNames))
	copy(strs, _ResourceTypeNames)
	return strs
}

// IsAResourceType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ResourceType) IsAResourceType() bool {
	for _, v := range _ResourceTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ResourceType
func (i ResourceType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ResourceType
func (i *ResourceType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ResourceType should be a string, got %s", data)
	}

	var err error
	*i, err = ResourceTypeString(s)
	return err
}
